export const stateOptions = [
  { label: "Madhya Pradesh", value: "MP" },
  { label: "Uttar Pradesh", value: "UP" },
  { label: "Gujrat", value: "GJ" },
];

export const divisionOptions = [
  { label: "Jabalpur", value: "JAB" },
  { label: "Rewa", value: "REW" },
  { label: "Gwalior", value: "GW" },
  { label: "Indore", value: "IN" },
  { label: "Ujjain", value: "Uj" },
  { label: "Shahdol", value: "SHA" },
];

export const districtOptions = [
  { label: "Jabalpur", value: "JAB_DIST" },
  { label: "Anuppur", value: "ANU" },
  { label: "Vidisha", value: "VID" },
];

export const blockOptions = [
  { label: "All", value: "all" },
  { label: "Phanda", value: "Ph" },
  { label: "Sehopur", value: "SE" },
  { label: "Ragogarh", value: "Rg" },
];

export const localBodyOptions = [
  { label: "Select Local Body", value: null },
  { label: "Nagar Panchayat", value: "np" },
  { label: "Janpad Panchayat", value: "np" },
];

export const zoneCodeOptions = [
  { label: "Select Village", value: null },
  { label: "SUDHARA-(20531)", value: "firo" },
  { label: "JHAKER-(20533)", value: "SEO" },
  { label: "NADIGAO-(20538)", value: "SEO" },
  { label: "SHYAMPUR-(20541)", value: "SEO" },
];

export const villageCodeOptions = [
  { label: "Select Village", value: null },
  { label: "Milawali-(107382)", value: "firo" },
  { label: "Sudhara-(107385)", value: "SEO" },
  { label: "Baddan-(107386)", value: "SEO" },
  { label: "Laxmanpura-(107399)", value: "SEO" },
];

export const stateMockData = [
  {
    id: 1,
    stateNameEn: "Jharkhand",
    stateNameHi: "Jharkhand",
    stateCode: "20",
    status: "Yes",
  },
  {
    id: 2,
    stateNameEn: "Uttar Pradesh",
    stateNameHi: "उत्तर प्रदेश",
    stateCode: "10",
    status: "Yes",
  },
  {
    id: 3,
    stateNameEn: "Punjab",
    stateNameHi: "Punjab",
    stateCode: "63",
    status: "No",
  },
  {
    id: 4,
    stateNameEn: "punjab",
    stateNameHi: "Punjab",
    stateCode: "89",
    status: "Yes",
  },
  {
    id: 5,
    stateNameEn: "PUNJAB",
    stateNameHi: "पंजाब",
    stateCode: "03",
    status: "Yes",
  },
  {
    id: 6,
    stateNameEn: "HIMACHAL PRADESH",
    stateNameHi: "हिमाचल प्रदेश",
    stateCode: "02",
    status: "Yes",
  },
  {
    id: 7,
    stateNameEn: "JAMMU AND KASHMIR",
    stateNameHi: "जम्मू एवं कश्मीर",
    stateCode: "01",
    status: "Yes",
  },
  {
    id: 8,
    stateNameEn: "Madhya Pradesh",
    stateNameHi: "मध्य प्रदेश",
    stateCode: "23",
    status: "Yes",
  },
  {
    id: 9,
    stateNameEn: "Gujarat",
    stateNameHi: "गुजरात",
    stateCode: "24",
    status: "Yes",
  },
];

export const divisionMockData = [
  {
    id: 1,
    stateName: "Madhya Pradesh",
    divisionNameEn: "Shahdol",
    divisionNameHi: "शहडोल",
    divisionCode: "10",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 2,
    stateName: "Madhya Pradesh",
    divisionNameEn: "Rewa",
    divisionNameHi: "रीवा",
    divisionCode: "9",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 3,
    stateName: "Madhya Pradesh",
    divisionNameEn: "Jabalpur",
    divisionNameHi: "जबलपुर",
    divisionCode: "8",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 4,
    stateName: "Madhya Pradesh",
    divisionNameEn: "Sagar",
    divisionNameHi: "सागर",
    divisionCode: "7",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 5,
    stateName: "Madhya Pradesh",
    divisionNameEn: "Narmadapuram",
    divisionNameHi: "नर्मदापुरम",
    divisionCode: "6",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 6,
    stateName: "Madhya Pradesh",
    divisionNameEn: "Bhopal",
    divisionNameHi: "भोपाल",
    divisionCode: "5",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 7,
    stateName: "Madhya Pradesh",
    divisionNameEn: "Indore",
    divisionNameHi: "इंदौर",
    divisionCode: "4",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 8,
    stateName: "Madhya Pradesh",
    divisionNameEn: "Ujjain",
    divisionNameHi: "उज्जैन",
    divisionCode: "3",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 9,
    stateName: "Madhya Pradesh",
    divisionNameEn: "Gwalior",
    divisionNameHi: "ग्वालियर",
    divisionCode: "2",
    lgdCode: "",
    status: "Yes",
  },
];

export const districtMockData = [
  {
    id: 1,
    stateName: "Madhya Pradesh",
    divisionName: "Jabalpur",
    districtNameEn: "Pandhurna",
    districtNameHi: "पांढुर्णा",
    districtCode: "55",
    lgdCode: "785",
    status: "Yes",
  },
  {
    id: 2,
    stateName: "Madhya Pradesh",
    divisionName: "Rewa",
    districtNameEn: "Maihar",
    districtNameHi: "मैहर",
    districtCode: "54",
    lgdCode: "784",
    status: "Yes",
  },
  {
    id: 3,
    stateName: "Madhya Pradesh",
    divisionName: "Rewa",
    districtNameEn: "Mauganj",
    districtNameHi: "मऊगंज",
    districtCode: "53",
    lgdCode: "766",
    status: "Yes",
  },
  {
    id: 4,
    stateName: "Madhya Pradesh",
    divisionName: "Shahdol",
    districtNameEn: "Anuppur",
    districtNameHi: "अनूपपुर",
    districtCode: "47",
    lgdCode: "390",
    status: "Yes",
  },
  {
    id: 5,
    stateName: "Madhya Pradesh",
    divisionName: "Jabalpur",
    districtNameEn: "Dindori",
    districtNameHi: "डिण्डौरी",
    districtCode: "41",
    lgdCode: "404",
    status: "Yes",
  },
  {
    id: 6,
    stateName: "Madhya Pradesh",
    divisionName: "Shahdol",
    districtNameEn: "Shahdol",
    districtNameHi: "शहडोल",
    districtCode: "16",
    lgdCode: "429",
    status: "Yes",
  },
  {
    id: 7,
    stateName: "Madhya Pradesh",
    divisionName: "Shahdol",
    districtNameEn: "Umaria",
    districtNameHi: "उमरिया",
    districtCode: "15",
    lgdCode: "436",
    status: "Yes",
  },
  {
    id: 8,
    stateName: "Madhya Pradesh",
    divisionName: "Rewa",
    districtNameEn: "Singrauli",
    districtNameHi: "सिंगरौली",
    districtCode: "50",
    lgdCode: "638",
    status: "Yes",
  },
  {
    id: 9,
    stateName: "Madhya Pradesh",
    divisionName: "Rewa",
    districtNameEn: "Sidhi",
    districtNameHi: "सीधी",
    districtCode: "17",
    lgdCode: "433",
    status: "Yes",
  },
  {
    id: 10,
    stateName: "Madhya Pradesh",
    divisionName: "Rewa",
    districtNameEn: "Rewa",
    districtNameHi: "रीवा",
    districtCode: "14",
    lgdCode: "424",
    status: "Yes",
  },
];

export const blockMockData = [
  {
    id: 1,
    stateName: "Madhya Pradesh",
    divisionName: "Jabalpur",
    districtName: "Jabalpur",
    blockNameEn: "Jabalpur URBAN- 2",
    blockNameHi: "जबलपुर अर्बन- 2",
    blockCode: "322",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 2,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Gwalior",
    blockNameEn: "Morar URBAN 2",
    blockNameHi: "मोरार अर्बन 2",
    blockCode: "321",
    lgdCode: "3851",
    status: "Yes",
  },
  {
    id: 3,
    stateName: "Madhya Pradesh",
    divisionName: "Indore",
    districtName: "Indore",
    blockNameEn: "Indore URBAN- 2",
    blockNameHi: "इंदौर अर्बन- 2",
    blockCode: "320",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 4,
    stateName: "Madhya Pradesh",
    divisionName: "Bhopal",
    districtName: "Bhopal",
    blockNameEn: "Phanda URBAN- Old City",
    blockNameHi: "फंदा शहरी पुराना शहर",
    blockCode: "319",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 5,
    stateName: "Madhya Pradesh",
    divisionName: "Indore",
    districtName: "Burhanpur",
    blockNameEn: "Khaknar",
    blockNameHi: "खकनार",
    blockCode: "318",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 6,
    stateName: "Madhya Pradesh",
    divisionName: "Indore",
    districtName: "Burhanpur",
    blockNameEn: "Burhanpur",
    blockNameHi: "बुरहानपुर",
    blockCode: "317",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 7,
    stateName: "Madhya Pradesh",
    divisionName: "Shahdol",
    districtName: "Anuppur",
    blockNameEn: "Pushpraj Garh",
    blockNameHi: "पुष्पराजगढ़",
    blockCode: "316",
    lgdCode: "3739",
    status: "Yes",
  },
  {
    id: 8,
    stateName: "Madhya Pradesh",
    divisionName: "Shahdol",
    districtName: "Anuppur",
    blockNameEn: "Kotma",
    blockNameHi: "कोतमा",
    blockCode: "315",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 9,
    stateName: "Madhya Pradesh",
    divisionName: "Shahdol",
    districtName: "Anuppur",
    blockNameEn: "Jaithari",
    blockNameHi: "जैतहरी",
    blockCode: "314",
    lgdCode: "",
    status: "Yes",
  },
  {
    id: 10,
    stateName: "Madhya Pradesh",
    divisionName: "Shahdol",
    districtName: "Anuppur",
    blockNameEn: "Anuppur",
    blockNameHi: "अनूपपुर",
    blockCode: "313",
    lgdCode: "",
    status: "Yes",
  },
];

export const villageMockData = [
  {
    id: 1,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Ashoknagar",
    localBodyName: "Nagar Panchayat Shadora",
    zonePanchayatName: "Zone 1 Nagar Panchayat Shadora",
    villageNameEn: "Ward 15 Shri Krishna Ward",
    villageNameHi: "वार्ड 15 श्री कृष्ण वार्ड",
    villageCode: "1299953",
    lgdCode: "1299953",
    status: "Yes",
  },
  {
    id: 2,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Ashoknagar",
    localBodyName: "Nagar Panchayat Shadora",
    zonePanchayatName: "Zone 1 Nagar Panchayat Shadora",
    villageNameEn: "Ward 14 Shiv Ward",
    villageNameHi: "वार्ड 14 शिव वार्ड",
    villageCode: "1299952",
    lgdCode: "1299952",
    status: "Yes",
  },
  {
    id: 3,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Ashoknagar",
    localBodyName: "Nagar Panchayat Shadora",
    zonePanchayatName: "Zone 1 Nagar Panchayat Shadora",
    villageNameEn: "Ward 13 Milk Chouki Ward",
    villageNameHi: "वार्ड 13 मिल्क चौकी वार्ड",
    villageCode: "1299951",
    lgdCode: "1299951",
    status: "Yes",
  },
  {
    id: 4,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Ashoknagar",
    localBodyName: "Nagar Panchayat Shadora",
    zonePanchayatName: "Zone 1 Nagar Panchayat Shadora",
    villageNameEn: "Ward 12 Moulana Ward",
    villageNameHi: "वार्ड 12 मौलाना वार्ड",
    villageCode: "1299950",
    lgdCode: "1299950",
    status: "Yes",
  },
  {
    id: 5,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Ashoknagar",
    localBodyName: "Nagar Panchayat Shadora",
    zonePanchayatName: "Zone 1 Nagar Panchayat Shadora",
    villageNameEn: "Ward 11 Azad Ward",
    villageNameHi: "वार्ड 11 आज़ाद वार्ड",
    villageCode: "1299949",
    lgdCode: "1299949",
    status: "Yes",
  },
  {
    id: 6,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Ashoknagar",
    localBodyName: "Nagar Panchayat Shadora",
    zonePanchayatName: "Zone 1 Nagar Panchayat Shadora",
    villageNameEn: "Ward 10 Mela Ground Ward",
    villageNameHi: "वार्ड 10 मेला ग्राउंड वार्ड",
    villageCode: "1299948",
    lgdCode: "1299948",
    status: "Yes",
  },
  {
    id: 7,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Ashoknagar",
    localBodyName: "Nagar Panchayat Shadora",
    zonePanchayatName: "Zone 1 Nagar Panchayat Shadora",
    villageNameEn: "Ward 9 Tekri Ward",
    villageNameHi: "वार्ड 9 टेकरी वार्ड",
    villageCode: "1299947",
    lgdCode: "1299947",
    status: "Yes",
  },
  {
    id: 8,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Ashoknagar",
    localBodyName: "Nagar Panchayat Shadora",
    zonePanchayatName: "Zone 1 Nagar Panchayat Shadora",
    villageNameEn: "Ward 8 Indra Nagar Ward",
    villageNameHi: "वार्ड 8 इंद्रा नगर वार्ड",
    villageCode: "1299946",
    lgdCode: "1299946",
    status: "Yes",
  },
  {
    id: 9,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Ashoknagar",
    localBodyName: "Nagar Panchayat Shadora",
    zonePanchayatName: "Zone 1 Nagar Panchayat Shadora",
    villageNameEn: "Ward 7 Mahaveer Ward",
    villageNameHi: "वार्ड 7 महावीर वार्ड",
    villageCode: "1299945",
    lgdCode: "1299945",
    status: "Yes",
  },
  {
    id: 10,
    stateName: "Madhya Pradesh",
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Ashoknagar",
    localBodyName: "Nagar Panchayat Shadora",
    zonePanchayatName: "Zone 1 Nagar Panchayat Shadora",
    villageNameEn: "Ward 6 Pandapura Ward",
    villageNameHi: "वार्ड 6 पांडापुरा वार्ड",
    villageCode: "1299944",
    lgdCode: "1299944",
    status: "Yes",
  },
];

export const habitationMockData = [
  {
    id: 1,
    divisionName: "Gwalior",
    districtName: "Morena",
    blockName: "Morena",
    zonePanchayatName: "zone panchayat name- firojour",
    villageName: "Firojour",
    habitationNameEn: "Firojour",
    habitationNameHi: "फिरोजपुर",
    habitationCode: "4566322",
    status: "Yes",
  },
  {
    id: 2,
    divisionName: "Gwalior",
    districtName: "Shivpuri",
    blockName: "Narvar",
    zonePanchayatName: "NAGAR PARISHAD MANGRONI",
    villageName: "Ward 1",
    habitationNameEn: "Ward 1",
    habitationNameHi: "वार्ड 1",
    habitationCode: "114360",
    status: "No",
  },
  {
    id: 3,
    divisionName: "Gwalior",
    districtName: "Sheopur",
    blockName: "Vijaypur",
    zonePanchayatName: "Neemuch",
    villageName: "Dhobipura",
    habitationNameEn: "Dhobipura",
    habitationNameHi: "धोबीपुरा",
    habitationCode: "127195",
    status: "Yes",
  },
  {
    id: 4,
    divisionName: "Gwalior",
    districtName: "Sheopur",
    blockName: "Vijaypur",
    zonePanchayatName: "JAMURDI",
    villageName: "Dhokri ka Tapra",
    habitationNameEn: "Dhokri ka Tapra",
    habitationNameHi: "धोकरी का टपरा",
    habitationCode: "127182",
    status: "Yes",
  },
  {
    id: 5,
    divisionName: "Gwalior",
    districtName: "Morena",
    blockName: "Ambah",
    zonePanchayatName: "KAMTARI",
    villageName: "Bhikam Singh ka pura",
    habitationNameEn: "Bhikam Singh ka pura",
    habitationNameHi: "भीकम सिंह का पुरा",
    habitationCode: "127149",
    status: "Yes",
  },
  {
    id: 6,
    divisionName: "Gwalior",
    districtName: "Morena",
    blockName: "Kailaras",
    zonePanchayatName: "kirawali mangarh",
    villageName: "Kirawali ka pura",
    habitationNameEn: "Kirawali ka pura",
    habitationNameHi: "किरावली का पुरा",
    habitationCode: "127132",
    status: "Yes",
  },
  {
    id: 7,
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Isagarh",
    zonePanchayatName: "KULWAR",
    villageName: "Naithai",
    habitationNameEn: "Naithai",
    habitationNameHi: "नाइथै",
    habitationCode: "126970",
    status: "Yes",
  },
  {
    id: 8,
    divisionName: "Gwalior",
    districtName: "Gwalior",
    blockName: "Ghatigaon",
    zonePanchayatName: "MEHADPUR (P)",
    villageName: "mheswra",
    habitationNameEn: "mheswra",
    habitationNameHi: "महेस्वरा",
    habitationCode: "126900",
    status: "Yes",
  },
  {
    id: 9,
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Mungawali",
    zonePanchayatName: "SINGHADA",
    villageName: "Dhondia",
    habitationNameEn: "Dhondia",
    habitationNameHi: "धोन्डिया",
    habitationCode: "126345",
    status: "Yes",
  },
  {
    id: 10,
    divisionName: "Gwalior",
    districtName: "Ashoknagar",
    blockName: "Mungawali",
    zonePanchayatName: "PATHRI",
    villageName: "pali",
    habitationNameEn: "pali",
    habitationNameHi: "पाली",
    habitationCode: "126341",
    status: "Yes",
  },
];

export const localBodyTypeMockData = [
  {
    id: 1,
    localBodyTypeNameEn: "Nagar Nigam",
    localBodyTypeNameHi: "",
    locationName: "Urban",
    localBodyTypeCode: "1",
    status: "Yes",
  },
  {
    id: 2,
    localBodyTypeNameEn: "Nagar Palika",
    localBodyTypeNameHi: "",
    locationName: "Urban",
    localBodyTypeCode: "2",
    status: "Yes",
  },
  {
    id: 3,
    localBodyTypeNameEn: "Nagar Praishad",
    localBodyTypeNameHi: "",
    locationName: "Urban",
    localBodyTypeCode: "3",
    status: "Yes",
  },
  {
    id: 4,
    localBodyTypeNameEn: "Gram Panchayat",
    localBodyTypeNameHi: "",
    locationName: "Rural",
    localBodyTypeCode: "4",
    status: "Yes",
  },
  {
    id: 5,
    localBodyTypeNameEn: "Jilla Panchayat",
    localBodyTypeNameHi: "",
    locationName: "Rural",
    localBodyTypeCode: "5",
    status: "Yes",
  },
  {
    id: 6,
    localBodyTypeNameEn: "Janpad Panchayat",
    localBodyTypeNameHi: "",
    locationName: "Rural",
    localBodyTypeCode: "6",
    status: "Yes",
  },
];

export const localBodyMockData = [
  {
    id: 1,
    divisionName: "Gwalior",
    districtName: "Guna",
    blockName: "Raghogarh",
    localBodyEn: "Madhusudangarh",
    localBodyHi: "मधुसूदनगढ़",
    localBodyCode: "299255",
    status: "Yes",
  },
  {
    id: 2,
    divisionName: "Indore",
    districtName: "Khargone",
    blockName: "Bhagwanpura",
    localBodyEn: "Zone 1, Nagar Parishad, Bistan 1",
    localBodyHi: "जोन 1, नगर परिषद्, बिस्तान 1",
    localBodyCode: "298930",
    status: "Yes",
  },
  {
    id: 3,
    divisionName: "Sagar",
    districtName: "Sagar",
    blockName: "Sagar",
    localBodyEn: "Makronia Buzurg",
    localBodyHi: "मकरोनिया बुजुर्ग",
    localBodyCode: "250766",
    status: "Yes",
  },
  {
    id: 4,
    divisionName: "Sagar",
    districtName: "Sagar",
    blockName: "Sagar",
    localBodyEn: "Surkhi",
    localBodyHi: "सुरखी",
    localBodyCode: "298934",
    status: "Yes",
  },
  {
    id: 5,
    divisionName: "Indore",
    districtName: "Khargone",
    blockName: "Gogawa",
    localBodyEn: "Zone 1, Nagar Parishad, Bistan",
    localBodyHi: "जोन 1, नगर परिषद्, बिस्तान",
    localBodyCode: "298931",
    status: "Yes",
  },
  {
    id: 6,
    divisionName: "Jabalpur",
    districtName: "Chhindwara",
    blockName: "Bichhua",
    localBodyEn: "Nagar Parishad Bichhua",
    localBodyHi: "नगर परिषद बिछुआ",
    localBodyCode: "263072",
    status: "Yes",
  },
  {
    id: 7,
    divisionName: "Shahdol",
    districtName: "Umaria",
    blockName: "Manpur",
    localBodyEn: "Nagar Parishad, Manpur",
    localBodyHi: "नगर परिषद, मानपुर",
    localBodyCode: "45644",
    status: "Yes",
  },
  {
    id: 8,
    divisionName: "Bhopal",
    districtName: "Sehore",
    blockName: "Budhani",
    localBodyEn: "Zone1 Nagar Parishad Shahganj",
    localBodyHi: "जोन 1 नगर परिषद शाहगंज",
    localBodyCode: "262903",
    status: "Yes",
  },
  {
    id: 9,
    divisionName: "Bhopal",
    districtName: "Sehore",
    blockName: "Ashta",
    localBodyEn: "Zone1 Nagar Parishad Kothri",
    localBodyHi: "जोन 1 नगर परिषद कोठरी",
    localBodyCode: "290383",
    status: "Yes",
  },
  {
    id: 10,
    divisionName: "Indore",
    districtName: "Barwani",
    blockName: "Raj Pur",
    localBodyEn: "ZONE-01 NAGAR PARISHAD PALSUD",
    localBodyHi: "जोन 1 नगर परिषद पालसूद",
    localBodyCode: "80001",
    status: "Yes",
  },
];

export const zonePanchayatMockData = [
  {
    id: 1,
    divisionName: "Rewa",
    districtName: "Maihar",
    blockName: "Amarpatan",
    localBodyName: "Janpad Panchayat, AMARPATAN",
    zonePanchayatEn: "Madha",
    zonePanchayatHi: "मढ़ा",
    zonePanchayatCode: "41554",
    status: "Yes",
  },
  {
    id: 2,
    divisionName: "Rewa",
    districtName: "Maihar",
    blockName: "Amarpatan",
    localBodyName: "Janpad Panchayat, AMARPATAN",
    zonePanchayatEn: "Semariya",
    zonePanchayatHi: "सेमरिया",
    zonePanchayatCode: "48594",
    status: "Yes",
  },
  {
    id: 3,
    divisionName: "Rewa",
    districtName: "Satna",
    blockName: "Rampur Baghelan",
    localBodyName: "Janpad Panchayat, RAMPUR BAGHELAN",
    zonePanchayatEn: "Mahudar",
    zonePanchayatHi: "महुडर",
    zonePanchayatCode: "5721",
    status: "Yes",
  },
  {
    id: 4,
    divisionName: "Rewa",
    districtName: "Satna",
    blockName: "Rampur Baghelan",
    localBodyName: "Janpad Panchayat, RAMPUR BAGHELAN",
    zonePanchayatEn: "Laami Karhi",
    zonePanchayatHi: "लामी करही",
    zonePanchayatCode: "57258",
    status: "No",
  },
  {
    id: 5,
    divisionName: "Indore",
    districtName: "Indore",
    blockName: "Sanwer",
    localBodyName: "Nagar Parishad, SANVER",
    zonePanchayatEn: "MAGARKHEDA/JAKHYA",
    zonePanchayatHi: "मगरखेड़ा जाख्या",
    zonePanchayatCode: "13453",
    status: "Yes",
  },
  {
    id: 6,
    divisionName: "Indore",
    districtName: "Indore",
    blockName: "Sanwer",
    localBodyName: "Janpad Panchayat, SANWER",
    zonePanchayatEn: "BHANWARASLA",
    zonePanchayatHi: "भंवरसला",
    zonePanchayatCode: "13452",
    status: "Yes",
  },
  {
    id: 7,
    divisionName: "Indore",
    districtName: "Indore",
    blockName: "Sanwer",
    localBodyName: "Janpad Panchayat, SANWER",
    zonePanchayatEn: "REVATI",
    zonePanchayatHi: "रेवती",
    zonePanchayatCode: "13451",
    status: "Yes",
  },
  {
    id: 8,
    divisionName: "Indore",
    districtName: "Indore",
    blockName: "Sanwer",
    localBodyName: "Janpad Panchayat, SANWER",
    zonePanchayatEn: "KUMEDI",
    zonePanchayatHi: "कुमेदी",
    zonePanchayatCode: "13450",
    status: "Yes",
  },
  {
    id: 9,
    divisionName: "Gwalior",
    districtName: "Guna",
    blockName: "Raghogarh",
    localBodyName: "Madhusudangarh",
    zonePanchayatEn: "Madhusudangarh",
    zonePanchayatHi: "मधुसूदनगढ़",
    zonePanchayatCode: "25633",
    status: "Yes",
  },
  {
    id: 10,
    divisionName: "Indore",
    districtName: "Khargone",
    blockName: "Bhagwanpura",
    localBodyEn: "Zone 1, Nagar Parishad, Bistan 1",
    zonePanchayatEn: "Ward 15- Banher",
    zonePanchayatHi: "वार्ड 15- बन्हेर",
    zonePanchayatCode: "25632",
    status: "Yes",
  },
];

export const tehsilMockData = [
  {
    id: 1,
    tehsilNameEn: "Vijaypur",
    tehsilNameHi: "विजयपुुुर",
    tehsilCode: "1",
    status: "Yes",
  },
  {
    id: 2,
    tehsilNameEn: "Beerpur",
    tehsilNameHi: "बीरपुर",
    tehsilCode: "2",
    status: "Yes",
  },
  {
    id: 3,
    tehsilNameEn: "Sheopur",
    tehsilNameHi: "श्योपुर",
    tehsilCode: "3",
    status: "Yes",
  },
  {
    id: 4,
    tehsilNameEn: "Badoda",
    tehsilNameHi: "बड़ोदा",
    tehsilCode: "4",
    status: "Yes",
  },
  {
    id: 5,
    tehsilNameEn: "Karahal",
    tehsilNameHi: "कराहल",
    tehsilCode: "5",
    status: "Yes",
  },
  {
    id: 6,
    tehsilNameEn: "Ambah",
    tehsilNameHi: "अंबाह",
    tehsilCode: "6",
    status: "Yes",
  },
  {
    id: 7,
    tehsilNameEn: "Porsa",
    tehsilNameHi: "पोरसा",
    tehsilCode: "7",
    status: "Yes",
  },
  {
    id: 8,
    tehsilNameEn: "Morena",
    tehsilNameHi: "मुरैना",
    tehsilCode: "8",
    status: "Yes",
  },
  {
    id: 9,
    tehsilNameEn: "Joura",
    tehsilNameHi: "जौरा",
    tehsilCode: "9",
    status: "Yes",
  },
  {
    id: 10,
    tehsilNameEn: "Kailaras",
    tehsilNameHi: "कैलारस",
    tehsilCode: "10",
    status: "Yes",
  },
];
