export const oisOptions = [
  { label: "Office", value: "OFFICE" },
  { label: "School", value: "SCHOOL" },
  { label: "Institute", value: "INSTITUTE" },
];

export const divisionOptions = [
  { label: "Bhopal", value: "BHOPAL" },
  { label: "Indore", value: "INDORE" },
  { label: "Gwalior", value: "GWALIOR" },
];

export const districtOptions = [
  { label: "Bhopal", value: "BHOPAL_DIST" },
  { label: "Vidisha", value: "VIDISHA" },
  { label: "Sehore", value: "SEHORE" },
];

export const blockOptions = [
  { label: "Berasia", value: "BERASIA" },
  { label: "Phanda", value: "PHANDA" },
];

export const verificationData = [
  {
    srNo: 1,
    employeeName: "Akhilesh Nigam [BU7621]",
    designation: "Asstt Grade-3",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 2,
    employeeName: "Anil Sharama [CA2412]",
    designation: "Peon-Regular",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 3,
    employeeName: "Ram Narayan Shrivastri [AA6580]",
    designation: "Principal HSS",
    actingDesignation: "Asstt Director",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
    rowClass: "bg-green-50",
  },
  {
    srNo: 4,
    employeeName: "Yashwant Sexena [AA4529]",
    designation: "Asstt Grade-2",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 5,
    employeeName: "Lakshminarayan Sen [AA4530]",
    designation: "Peon-Regular",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 6,
    employeeName: "Ram Ayodhya Prasad [AU2792]",
    designation: "Principal HSS",
    actingDesignation: "NA",
    panelSubject: "PR-HSS",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Reject",
  },
  {
    srNo: 7,
    employeeName: "Avadh Vihari Mishra [BK2296]",
    designation: "Peon-Regular",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 8,
    employeeName: "REENA DANGI [CC6697]",
    designation: "Asstt Grade-3",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 9,
    employeeName: "Rajeev Bhargava [AA4995]",
    designation: "Asstt Teacher(LDT)",
    actingDesignation: "NA",
    panelSubject: "SSS-3 General",
    postingOffice: "BRC, BERAISA [233201OBS02]",
    status: "Pending",
  },
  {
    srNo: 10,
    employeeName: "Rajesh Kumar Namdev [AB1189]",
    designation: "Madhyamik Shikshak",
    actingDesignation: "NA",
    panelSubject: "SSS-2 Social Science",
    postingOffice: "BRC, BERAISA [233201OBS02]",
    status: "Pending",
  },
];

export const hoVerificationData = [
  {
    srNo: 1,
    employeeName: "Yashwant Sexena [AA4529]",
    designation: "Asstt Grade-2",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 2,
    employeeName: "Akhilesh Nigam [BU7621]",
    designation: "Asstt Grade-3",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 3,
    employeeName: "REENA DANGI [CC6697]",
    designation: "Asstt Grade-3",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 4,
    employeeName: "Avadh Vihari Mishra [BK2296]",
    designation: "Peon-Regular",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 5,
    employeeName: "Anil Sharama [CA2412]",
    designation: "Peon-Regular",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 6,
    employeeName: "Lakshminarayan Sen [AA4530]",
    designation: "Peon-Regular",
    actingDesignation: "NA",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 7,
    employeeName: "Rajeev Bhargava [AA4995]",
    designation: "Asstt Teacher(LDT)",
    actingDesignation: "NA",
    panelSubject: "SSS-3 General",
    postingOffice: "BRC, BERAISA [233201OBS02]",
    status: "Pending",
  },
  {
    srNo: 8,
    employeeName: "Rajesh Kumar Namdev [AB1189]",
    designation: "Madhyamik Shikshak",
    actingDesignation: "NA",
    panelSubject: "SSS-2 Social Science",
    postingOffice: "BRC, BERAISA [233201OBS02]",
    status: "Pending",
  },
  {
    srNo: 9,
    employeeName: "Ram Ayodhya Prasad [AU2792]",
    designation: "Principal HSS",
    actingDesignation: "NA",
    panelSubject: "PR-HSS",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Reject",
  },
  {
    srNo: 10,
    employeeName: "Ram Narayan Shrivastri [AA6580]",
    designation: "Principal HSS",
    actingDesignation: "Asstt Director",
    panelSubject: "NA",
    postingOffice: "BEO, BERASIA [233201OBS01]",
    status: "Pending",
  },
];

export const pdfVerificationData = [
  {
    srNo: 1,
    blockName: "Berasia",
    employeeName: "Dharma Bagde [AT9310]",
    empUniqueId: "AT9310",
    postingOfficeCode: "23320110008",
    designationName: "Principal HSS",
  },
  {
    srNo: 2,
    blockName: "Berasia",
    employeeName: "Rakesh Kumar Jhariya [AA3732]",
    empUniqueId: "AA3732",
    postingOfficeCode: "23320110206",
    designationName: "Principal HSS",
  },
  {
    srNo: 3,
    blockName: "Berasia",
    employeeName: "Aabida Raza [AA4959]",
    empUniqueId: "AA4959",
    postingOfficeCode: "23320124510",
    designationName: "Principal HSS",
  },
  {
    srNo: 4,
    blockName: "Berasia",
    employeeName: "Vijaya Lingaiah [BP5330]",
    empUniqueId: "BP5330",
    postingOfficeCode: "23320120607",
    designationName: "Principal HSS",
  },
  {
    srNo: 5,
    blockName: "Berasia",
    employeeName: "Seema Mahajan [BP5338]",
    empUniqueId: "BP5338",
    postingOfficeCode: "23320113104",
    designationName: "Principal HS",
  },
  {
    srNo: 6,
    blockName: "Berasia",
    employeeName: "Shreeprakash Vijayvargiya [BP4186]",
    empUniqueId: "BP4186",
    postingOfficeCode: "23320124510",
    designationName: "Principal HS",
  },
  {
    srNo: 7,
    blockName: "Berasia",
    employeeName: "Kirti Nandini Saxena [AA1015]",
    empUniqueId: "AA1015",
    postingOfficeCode: "23320110008",
    designationName: "Principal HS",
  },
  {
    srNo: 8,
    blockName: "Berasia",
    employeeName: "Gaytri Sikanwar [BG1725]",
    empUniqueId: "BG1725",
    postingOfficeCode: "23320126802",
    designationName: "Principal HS",
  },
  {
    srNo: 9,
    blockName: "Berasia",
    employeeName: "Sandhya Singh Kumar [AA4723]",
    empUniqueId: "AA4723",
    postingOfficeCode: "23320125506",
    designationName: "Principal HS",
  },
  {
    srNo: 10,
    blockName: "Berasia",
    employeeName: "Jagbhan Singh [AA3574]",
    empUniqueId: "AA3574",
    postingOfficeCode: "23320120707",
    designationName: "Principal HS",
  },
];

export const officialUpdateData = [
  {
    srNo: 1,
    employeeName: "Praveena Kaushal [CA1689]",
    designation: "Principal HS",
    postingOffice: "Director, Public Instructions [233203OSD03]",
    emailId: "",
    mobileNo: "9753093780",
    panelName: "PR-HSS",
  },
  {
    srNo: 2,
    employeeName: "Ravindra Uikey [CA1693]",
    designation: "Asstt Grade-3",
    postingOffice: "Director, Public Instructions [233203OSD03]",
    emailId: "geniusravi1@gmail.com",
    mobileNo: "9826336420",
    panelName: "NA",
  },
];

export const directoryStats = [
  {
    label: "Total Employees",
    count: "12,840",
    icon: "pi-users",
    color: "#9333ea",
    trend: "↑ 4% growth",
  },
  {
    label: "Pending Verifications",
    count: "842",
    icon: "pi-user-edit",
    color: "#a855f7",
    trend: "12 high priority",
  },
  {
    label: "HO Level Pending",
    count: "156",
    icon: "pi-shield",
    color: "#7e22ce",
    trend: "Across 5 departments",
  },
  {
    label: "Update Requests",
    count: "2,105",
    icon: "pi-sync",
    color: "#6b21a8",
    trend: "85% processed",
  },
];

export const registrationChartData = {
  labels: ["Registered", "In-Progress", "Verification Pending"],
  datasets: [
    {
      data: [8200, 2100, 2540],
      backgroundColor: ["#7e22ce", "#a855f7", "#e9d5ff"],
      borderWidth: 0,
    },
  ],
};

export const recentActivity = [
  {
    id: "EMP-9021",
    name: "Anil Sharma",
    request: "Official Details Update",
    date: "12 Jan 2026",
    status: "In-Progress",
  },
  {
    id: "EMP-4432",
    name: "Praveena Kaushal",
    request: "Data Change Request",
    date: "11 Jan 2026",
    status: "Verified",
  },
  {
    id: "EMP-8812",
    name: "Yashwant Sexena",
    request: "HO Level Verification",
    date: "10 Jan 2026",
    status: "Pending",
  },
  {
    id: "EMP-3321",
    name: "Rajesh Kumar",
    request: "Employee Registration",
    date: "10 Jan 2026",
    status: "Verified",
  },
];
