export const vargOptions = [
  { label: "Varg1", value: "Varg1" },
  { label: "Varg2", value: "Varg2" },
  { label: "Varg3", value: "Varg3" },
];

export const divisionOptions = [
  { label: "Rewa", value: "Rewa" },
  { label: "Bhopal", value: "Bhopal" },
  { label: "Sagar", value: "Sagar" },
];

export const districtOptions = [
  { label: "Rewa", value: "Rewa" },
  { label: "Sehore", value: "Sehore" },
  { label: "Tikamgarh", value: "Tikamgarh" },
];

export const blockOptions = [
  { label: "Sirmour", value: "Sirmour" },
  { label: "Sehore", value: "Sehore" },
];

export const schoolOptions = [
  { label: "GHSS Excellence Sirmour", value: "23140417005" },
  { label: "GHSS Bilkisganj", value: "23330507518" },
];

export const officeTypeMockData = [
  {
    id: 1,
    oisType: "Office",
    officeLevel: "State Level",
    officeTypeNameEn: "DPI DEMO II",
    officeTypeNameHi: "डीपीआई डेमो II",
    officeTypeCode: "80",
    status: "Yes",
  },
  {
    id: 2,
    oisType: "Office",
    officeLevel: "District Level",
    officeTypeNameEn: "DEO DEMO",
    officeTypeNameHi: "DEO DEMO",
    officeTypeCode: "45",
    status: "Yes",
  },
  {
    id: 3,
    oisType: "Office",
    officeLevel: "State Level",
    officeTypeNameEn: "DPI Demo",
    officeTypeNameHi: "DPI Demo",
    officeTypeCode: "44",
    status: "Yes",
  },
  {
    id: 4,
    oisType: "Office",
    officeLevel: "State Level",
    officeTypeNameEn: "CMRISE",
    officeTypeNameHi: "CMRISE",
    officeTypeCode: "43",
    status: "Yes",
  },
  {
    id: 5,
    oisType: "Office",
    officeLevel: "State Level",
    officeTypeNameEn: "NCC",
    officeTypeNameHi: "NCC",
    officeTypeCode: "42",
    status: "Yes",
  },
  {
    id: 6,
    oisType: "Office",
    officeLevel: "State Level",
    officeTypeNameEn: "SCOUTS",
    officeTypeNameHi: "SCOUTS",
    officeTypeCode: "41",
    status: "Yes",
  },
  {
    id: 7,
    oisType: "Office",
    officeLevel: "State Level",
    officeTypeNameEn: "TBC",
    officeTypeNameHi: "TBC",
    officeTypeCode: "40",
    status: "Yes",
  },
  {
    id: 8,
    oisType: "Office",
    officeLevel: "State Level",
    officeTypeNameEn: "MADARSA BOARD",
    officeTypeNameHi: "MADARSA BOARD",
    officeTypeCode: "39",
    status: "Yes",
  },
];

export const schoolTypeMockData = [
  {
    id: 1,
    schoolTypeNameEn: "Boys",
    schoolTypeNameHi: "बॉयज़",
    schoolTypeCode: "01",
    status: "Yes",
  },
  {
    id: 2,
    schoolTypeNameEn: "Girls",
    schoolTypeNameHi: "गर्ल्स",
    schoolTypeCode: "02",
    status: "Yes",
  },
  {
    id: 3,
    schoolTypeNameEn: "Co-Educational",
    schoolTypeNameHi: "को - एजुकेशनल",
    schoolTypeCode: "03",
    status: "Yes",
  },
];

export const schoolManagementGroupMockData = [
  {
    id: 1,
    groupNameEn: "Other",
    groupNameHi: "अन्य",
    groupCode: "E",
    status: "Yes",
  },
  {
    id: 2,
    groupNameEn: "Central Government",
    groupNameHi: "केंद्र सरकार",
    groupCode: "D",
    status: "Yes",
  },
  {
    id: 3,
    groupNameEn: "Private Unaided (Recognized)",
    groupNameHi: "निजी गैर सहायता प्राप्त (मान्यता प्राप्त)",
    groupCode: "C",
    status: "Yes",
  },
  {
    id: 4,
    groupNameEn: "Government Aided",
    groupNameHi: "सरकारी सहायता प्राप्त",
    groupCode: "B",
    status: "Yes",
  },
  {
    id: 5,
    groupNameEn: "State Government",
    groupNameHi: "राज्य सरकार",
    groupCode: "A",
    status: "Yes",
  },
];

export const managementGroupDetailMockData = [
  {
    id: 1,
    groupName: "Other",
    detailNameEn: "Others",
    detailNameHi: "Others",
    detailCode: "103",
    status: "Yes",
  },
  {
    id: 2,
    groupName: "Central Government",
    detailNameEn: "Sainik School (PPP)",
    detailNameHi: "सैनिक स्कूल (पीपीपी)",
    detailCode: "102",
    status: "Yes",
  },
  {
    id: 3,
    groupName: "Other",
    detailNameEn: "Madarsa Unrecognized",
    detailNameHi: "मदरसा गैर मान्यता प्राप्त",
    detailCode: "98",
    status: "Yes",
  },
  {
    id: 4,
    groupName: "Other",
    detailNameEn: "Madrasa Aided (Recognized)",
    detailNameHi: "मदरसा सहायता प्राप्त (मान्यता प्राप्त)",
    detailCode: "99",
    status: "Yes",
  },
  {
    id: 5,
    groupName: "Other",
    detailNameEn: "Madrasa Private Unaided (Recognized)",
    detailNameHi: "मदरसा निजी गैर सहायता प्राप्त (मान्यता प्राप्त)",
    detailCode: "97",
    status: "Yes",
  },
  {
    id: 6,
    groupName: "Other",
    detailNameEn: "Unrecognized",
    detailNameHi: "गैर-मान्यता प्राप्त",
    detailCode: "8",
    status: "Yes",
  },
  {
    id: 7,
    groupName: "Central Government",
    detailNameEn: "Other Central Govt./PSU Schools**",
    detailNameHi: "अन्य केंद्रीय सरकार/पीएसयू स्कूल**",
    detailCode: "101",
    status: "Yes",
  },
  {
    id: 8,
    groupName: "Central Government",
    detailNameEn: "Central Tibetan School",
    detailNameHi: "सेंट्रल तिब्बती स्कूल",
    detailCode: "96",
    status: "Yes",
  },
];

export const schoolBoardMockData = [
  {
    id: 1,
    boardNameEn: "Both CBSE & State Board",
    boardNameHi: "Both CBSE & State Board",
    boardCode: "11",
    status: "Yes",
  },
  {
    id: 2,
    boardNameEn: "Others",
    boardNameHi: "Others",
    boardCode: "10",
    status: "Yes",
  },
  {
    id: 3,
    boardNameEn: "International Board",
    boardNameHi: "International Board",
    boardCode: "9",
    status: "Yes",
  },
  {
    id: 4,
    boardNameEn: "Madarasa Board",
    boardNameHi: "Madarasa Board",
    boardCode: "8",
    status: "Yes",
  },
  {
    id: 5,
    boardNameEn: "Affiliated to Any Other Board",
    boardNameHi: "Affiliated to any other Board",
    boardCode: "7",
    status: "Yes",
  },
  {
    id: 6,
    boardNameEn: "Sanskrit Board",
    boardNameHi: "Sanskrit Board",
    boardCode: "5",
    status: "Yes",
  },
  {
    id: 7,
    boardNameEn: "ICSE",
    boardNameHi: "ICSE",
    boardCode: "3",
    status: "Yes",
  },
  {
    id: 8,
    boardNameEn: "CBSE",
    boardNameHi: "CBSE",
    boardCode: "2",
    status: "Yes",
  },
];

export const schoolCategoryMockData = [
  {
    id: 1,
    officeType: "",
    categoryNameEn: "Pre-Primary School",
    categoryNameHi: "प्री-प्राइमरी स्कूल",
    categoryCode: "05",
    status: "Yes",
  },
  {
    id: 2,
    officeType: "HSS",
    categoryNameEn: "Higher Secondary School",
    categoryNameHi: "हायर सेकेंडरी स्कूल",
    categoryCode: "04",
    status: "Yes",
  },
  {
    id: 3,
    officeType: "HS",
    categoryNameEn: "Secondary School",
    categoryNameHi: "माध्यमिक स्कूल",
    categoryCode: "03",
    status: "Yes",
  },
  {
    id: 4,
    officeType: "MS",
    categoryNameEn: "Upper primary School",
    categoryNameHi: "उच्च प्राथमिक स्कूल",
    categoryCode: "02",
    status: "Yes",
  },
  {
    id: 5,
    officeType: "PS",
    categoryNameEn: "Primary School",
    categoryNameHi: "प्राथमिक स्कूल",
    categoryCode: "01",
    status: "Yes",
  },
];

export const schoolSubCategoryMockData = [
  {
    id: 1,
    schoolCategory: "Higher Secondary School",
    detailEn: "Higher Secondary with grade k.g. to 12",
    detailCode: "15",
    status: "Yes",
  },
  {
    id: 2,
    schoolCategory: "Secondary School",
    detailEn: "Secondary with grade K.G. to 10",
    detailCode: "14",
    status: "Yes",
  },
  {
    id: 3,
    schoolCategory: "Upper primary School",
    detailEn: "Upper Primary only with K.G. to 8",
    detailCode: "13",
    status: "Yes",
  },
  {
    id: 4,
    schoolCategory: "Primary School",
    detailEn: "Primary only with grades K.G. to 5",
    detailCode: "12",
    status: "Yes",
  },
  {
    id: 5,
    schoolCategory: "Higher Secondary School",
    detailEn: "Hr. Sec./Jr. College only with grades 11 & 12 (HSEC)",
    detailCode: "11",
    status: "Yes",
  },
  {
    id: 6,
    schoolCategory: "Higher Secondary School",
    detailEn: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    detailCode: "3",
    status: "Yes",
  },
  {
    id: 7,
    schoolCategory: "Higher Secondary School",
    detailEn: "Higher Secondary with grades 9 to 12 (SEC-HSEC)",
    detailCode: "7",
    status: "Yes",
  },
  {
    id: 8,
    schoolCategory: "Higher Secondary School",
    detailEn: "Higher Secondary with grades 6 to 12 (UPR-SEC-HSEC)",
    detailCode: "5",
    status: "Yes",
  },
];

export const schoolInchargeTypeMockData = [
  {
    id: 1,
    inchargeTypeEn: "Others",
    inchargeTypeHi: "अन्य",
    inchargeCode: "6",
    status: "Yes",
  },
  {
    id: 2,
    inchargeTypeEn: "In-Charge from Block/District",
    inchargeTypeHi: "ब्लॉक/जिला से प्रभारी",
    inchargeCode: "5",
    status: "Yes",
  },
  {
    id: 3,
    inchargeTypeEn: "In-Charge from Other School",
    inchargeTypeHi: "अन्य विद्यालय से प्रभारी",
    inchargeCode: "4",
    status: "Yes",
  },
  {
    id: 4,
    inchargeTypeEn: "Acting Head Teacher",
    inchargeTypeHi: "कार्यवाहक प्रधान शिक्षक",
    inchargeCode: "3",
    status: "Yes",
  },
  {
    id: 5,
    inchargeTypeEn: "Asst. Head Master/Vice Principal",
    inchargeTypeHi: "सहा. हेड मास्टर/उप प्राचार्य",
    inchargeCode: "2",
    status: "Yes",
  },
  {
    id: 6,
    inchargeTypeEn: "Head Master/Principal",
    inchargeTypeHi: "हेड मास्टर/प्रिंसिपल",
    inchargeCode: "1",
    status: "Yes",
  },
];

export const schoolMediumMockData = [
  {
    id: 1,
    mediumNameEn: "Hindi",
    mediumNameHi: "Hindi",
    mediumCode: "1",
    status: "Yes",
  },
  {
    id: 2,
    mediumNameEn: "English",
    mediumNameHi: "English",
    mediumCode: "2",
    status: "Yes",
  },
  {
    id: 3,
    mediumNameEn: "Sanskrit",
    mediumNameHi: "Sanskrit",
    mediumCode: "3",
    status: "Yes",
  },
  {
    id: 4,
    mediumNameEn: "Urdu",
    mediumNameHi: "Urdu",
    mediumCode: "4",
    status: "Yes",
  },
  {
    id: 5,
    mediumNameEn: "Marathi",
    mediumNameHi: "Marathi",
    mediumCode: "5",
    status: "Yes",
  },
  {
    id: 6,
    mediumNameEn: "Sindhi",
    mediumNameHi: "Sindhi",
    mediumCode: "6",
    status: "Yes",
  },
  {
    id: 7,
    mediumNameEn: "None",
    mediumNameHi: "None",
    mediumCode: "7",
    status: "Yes",
  },
  {
    id: 8,
    mediumNameEn: "Hindi + English",
    mediumNameHi: "हिंदी + अंग्रेजी",
    mediumCode: "8",
    status: "Yes",
  },
];

export const specialSchoolMockData = [
  {
    id: 1,
    vargName: "",
    subjectEn: "Computer Science",
    subjectHi: "कंप्यूटर विज्ञान",
    subjectCode: "00",
    status: "Yes",
  },
  {
    id: 2,
    vargName: "",
    subjectEn: "MBA (Finance)",
    subjectHi: "एमबीए (वित्त)",
    subjectCode: "00",
    status: "Yes",
  },
  {
    id: 3,
    vargName: "Varg1",
    subjectEn: "M.Ed",
    subjectHi: "एम.एड",
    subjectCode: "00",
    status: "Yes",
  },
  {
    id: 4,
    vargName: "Varg3",
    subjectEn: "D.Ed.",
    subjectHi: "डी.एड.",
    subjectCode: "00",
    status: "Yes",
  },
  {
    id: 5,
    vargName: "Varg2",
    subjectEn: "B.Ed.(Special Education)",
    subjectHi: "बी.एड. (विशेष शिक्षा)",
    subjectCode: "00",
    status: "Yes",
  },
  {
    id: 6,
    vargName: "Varg2",
    subjectEn: "B.Ed.",
    subjectHi: "बी.एड",
    subjectCode: "00",
    status: "Yes",
  },
  {
    id: 7,
    vargName: "",
    subjectEn: "All",
    subjectHi: "सभी",
    subjectCode: "00",
    status: "Yes",
  },
  {
    id: 8,
    vargName: "Varg2",
    subjectEn: "Craft",
    subjectHi: "शिल्प",
    subjectCode: "47",
    status: "Yes",
  },
];

export const specialSchoolMasterMockData = [
  {
    id: 1,
    specialSchoolNameEn: "CM Rise School",
    specialSchoolNameHi: "सीएम राइज स्कूल",
    specialSchoolCode: "01",
    status: "Yes",
  },
  {
    id: 2,
    specialSchoolNameEn: "Model School",
    specialSchoolNameHi: "मॉडल स्कूल",
    specialSchoolCode: "02",
    status: "Yes",
  },
  {
    id: 3,
    specialSchoolNameEn: "CM Rise / Model (Both) School",
    specialSchoolNameHi: "सीएम राइज/मॉडल दोनों",
    specialSchoolCode: "03",
    status: "Yes",
  },
  {
    id: 4,
    specialSchoolNameEn: "District Excellence School",
    specialSchoolNameHi: "जिला उत्कृष्ट विद्यालय",
    specialSchoolCode: "04",
    status: "Yes",
  },
  {
    id: 5,
    specialSchoolNameEn: "Block Excellence School",
    specialSchoolNameHi: "ब्लॉक उत्कृष्ट विद्यालय",
    specialSchoolCode: "05",
    status: "Yes",
  },
  {
    id: 6,
    specialSchoolNameEn: "PM Shri School",
    specialSchoolNameHi: "पीएम श्री स्कूल",
    specialSchoolCode: "06",
    status: "Yes",
  },
  {
    id: 7,
    specialSchoolNameEn: "CWSN School",
    specialSchoolNameHi: "सीडब्ल्यूएसएन स्कूल",
    specialSchoolCode: "07",
    status: "Yes",
  },
  {
    id: 8,
    specialSchoolNameEn: "EFA School",
    specialSchoolNameHi: "ईएफए स्कूल",
    specialSchoolCode: "08",
    status: "Yes",
  },
];

export const schoolClassNameMockData = [
  {
    id: 1,
    classNameEn: "Class - 1",
    classNameHi: "कक्षा - 1",
    classCode: "01",
    status: "Yes",
  },
  {
    id: 2,
    classNameEn: "Class - 2",
    classNameHi: "कक्षा - 2",
    classCode: "02",
    status: "Yes",
  },
  {
    id: 3,
    classNameEn: "Class - 3",
    classNameHi: "कक्षा - 3",
    classCode: "03",
    status: "Yes",
  },
  {
    id: 4,
    classNameEn: "Class - 4",
    classNameHi: "कक्षा - 4",
    classCode: "04",
    status: "Yes",
  },
  {
    id: 5,
    classNameEn: "Class - 5",
    classNameHi: "कक्षा - 5",
    classCode: "05",
    status: "Yes",
  },
  {
    id: 6,
    classNameEn: "Class - 6",
    classNameHi: "कक्षा - 6",
    classCode: "06",
    status: "Yes",
  },
  {
    id: 7,
    classNameEn: "Class - 7",
    classNameHi: "कक्षा - 7",
    classCode: "07",
    status: "Yes",
  },
  {
    id: 8,
    classNameEn: "Class - 8",
    classNameHi: "कक्षा - 8",
    classCode: "08",
    status: "Yes",
  },
  {
    id: 8,
    classNameEn: "Class - 9",
    classNameHi: "कक्षा - 9",
    classCode: "09",
    status: "Yes",
  },
  {
    id: 8,
    classNameEn: "Class - 10",
    classNameHi: "कक्षा - 10",
    classCode: "10",
    status: "Yes",
  },
  {
    id: 8,
    classNameEn: "Class - 11",
    classNameHi: "कक्षा - 11",
    classCode: "11",
    status: "Yes",
  },
  {
    id: 8,
    classNameEn: "Class - 12",
    classNameHi: "कक्षा - 12",
    classCode: "12",
    status: "Yes",
  },
];

export const jskMockData = [
  {
    id: 1,
    divisionName: "Rewa",
    districtName: "Rewa",
    blockName: "Sirmour",
    jskNameEn: "CMRISE -GHSS EXCELLENCE SIRMOUR (6-12)",
    jskNameHi: "CMRISE -GHSS EXCELLENCE SIRMOUR (6-12)",
    jskCode: "23140417005",
    status: "Yes",
  },
  {
    id: 2,
    divisionName: "Bhopal",
    districtName: "Sehore",
    blockName: "Sehore",
    jskNameEn: "CMRISE -GHSS BILKISGANJ (6-12)",
    jskNameHi: "CMRISE -GHSS BILKISGANJ (6-12)",
    jskCode: "23330507518",
    status: "Yes",
  },
  {
    id: 3,
    divisionName: "Jabalpur",
    districtName: "Jabalpur",
    blockName: "Patan",
    jskNameEn: "CMRISE -GHSS EXCELLENCE, PATAN (6-12)",
    jskNameHi: "CMRISE -GHSS EXCELLENCE, PATAN (6-12)",
    jskCode: "23390513419",
    status: "Yes",
  },
  {
    id: 4,
    divisionName: "Bhopal",
    districtName: "Raisen",
    blockName: "Udaipura",
    jskNameEn: "CMRISE-BOYS HSS UDAIPURA(9-12)",
    jskNameHi: "CMRISE-BOYS HSS UDAIPURA(9-12)",
    jskCode: "23340715239",
    status: "Yes",
  },
  {
    id: 5,
    divisionName: "Bhopal",
    districtName: "Sehore",
    blockName: "Ashta",
    jskNameEn: "CMRISE-GHSS EXCELLENCE, ASHTA (9-12)",
    jskNameHi: "CMRISE-GHSS EXCELLENCE, ASHTA (9-12)",
    jskCode: "23330132647",
    status: "Yes",
  },
  {
    id: 6,
    divisionName: "Sagar",
    districtName: "Tikamgarh",
    blockName: "Jatara",
    jskNameEn: "EPES GGHS CHANDERA(CLASS 1 TO 10)",
    jskNameHi: "GGHS CHANDERA",
    jskCode: "23080212318",
    status: "Yes",
  },
  {
    id: 7,
    divisionName: "Sagar",
    districtName: "Niwari",
    blockName: "Niwari",
    jskNameEn: "EPES GHSS NO2 NIWARI",
    jskNameHi: "EPES GHSS NO2 NIWARI",
    jskCode: "23520315636",
    status: "Yes",
  },
  {
    id: 8,
    divisionName: "Sagar",
    districtName: "Tikamgarh",
    blockName: "Palera",
    jskNameEn: "EPES GHSS SYAWANI (6-12)",
    jskNameHi: "GHSS SYAWANI 6-12",
    jskCode: "23080402604",
    status: "Yes",
  },
  {
    id: 9,
    divisionName: "Gwalior",
    districtName: "Morena",
    blockName: "Morena",
    jskNameEn: "EPES-GOVT.M.S./H.S. KHARAGPUR BHARRAND (6 to 12)",
    jskNameHi: "शा०मा०हाईस्कूल वि० खरगपुर भर्राड 6 से 10",
    jskCode: "23020310106",
    status: "Yes",
  },
  {
    id: 10,
    divisionName: "Ujjain",
    districtName: "Ujjain",
    blockName: "Tarana",
    jskNameEn: "G EPES HSS KANASIYA (1 to 12)",
    jskNameHi: "G EPES HSS KANASIYA (1 to 12)",
    jskCode: "23210520717",
    status: "Yes",
  },
];

export const classToSubjectMockData = [];

export const schoolSubCategoryMappingMockData = [
  {
    id: 1,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 1",
    classCode: "01",
  },
  {
    id: 2,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 2",
    classCode: "02",
  },
  {
    id: 3,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 3",
    classCode: "03",
  },
  {
    id: 4,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 4",
    classCode: "04",
  },
  {
    id: 5,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 5",
    classCode: "05",
  },
  {
    id: 6,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 6",
    classCode: "06",
  },
  {
    id: 7,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 7",
    classCode: "07",
  },
  {
    id: 8,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 8",
    classCode: "08",
  },
  {
    id: 9,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 9",
    classCode: "09",
  },
  {
    id: 10,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 10",
    classCode: "10",
  },
];

export const designationMappingMockData = [
  {
    id: 1,
    levelName: "School",
    designationName: "Accounts Officer (Class-II) -150",
    status: "Yes",
  },
  {
    id: 2,
    levelName: "School",
    designationName: "Accounts Officer (Class-I) -149",
    status: "Yes",
  },
  {
    id: 3,
    levelName: "School",
    designationName: "Accountant -36",
    status: "Yes",
  },
  {
    id: 4,
    levelName: "Institute",
    designationName: "Lecturer (DIET) -199",
    status: "Yes",
  },
  {
    id: 5,
    levelName: "Institute",
    designationName: "Principal HS -14",
    status: "Yes",
  },
  {
    id: 6,
    levelName: "Institute",
    designationName: "Principal HSS -13",
    status: "Yes",
  },
  {
    id: 7,
    levelName: "Institute",
    designationName: "Regional Librarian -7",
    status: "Yes",
  },
  {
    id: 8,
    levelName: "Institute",
    designationName: "Additional Director -3",
    status: "Yes",
  },
  {
    id: 9,
    levelName: "Institute",
    designationName: "Director -2",
    status: "Yes",
  },
];

export const officeLevelOptions = [
  { label: "School", value: "School" },
  { label: "Institute", value: "Institute" },
  { label: "District Office", value: "District Office" },
];
