export const oisOptions = [
  { label: "Office", value: "OFFICE" },
  { label: "School", value: "SCHOOL" },
  { label: "Institute", value: "INSTITUTE" },
];

export const academicYearOptions = [
  { label: "2025-26", value: "2025-26" },
  { label: "2024-25", value: "2024-25" },
  { label: "2023-24", value: "2023-24" },
];

export const handicappedTypeOptions = [
  { label: "Locomotor Disability", value: "LD" },
  { label: "Visual Impairment", value: "VI" },
  { label: "Hearing Impairment", value: "HI" },
  { label: "Mental Retardation", value: "MR" },
  { label: "Multiple Disability", value: "MD" },
  { label: "All", value: "ALL" },
];

export const statisticReportData = [
  {
    srNo: 1,
    division: "Bhopal",
    district: "Raisen",
    totalRegistered: 78,
    profileChecked: 78,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
  {
    srNo: 2,
    division: "Bhopal",
    district: "Rajgarh",
    totalRegistered: 2,
    profileChecked: 2,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
  {
    srNo: 3,
    division: "Bhopal",
    district: "Sehore",
    totalRegistered: 17,
    profileChecked: 17,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
  {
    srNo: 4,
    division: "Bhopal",
    district: "Vidisha",
    totalRegistered: 17,
    profileChecked: 17,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
  {
    srNo: 5,
    division: "Gwalior",
    district: "Bhind",
    totalRegistered: 35,
    profileChecked: 35,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
  {
    srNo: 6,
    division: "Gwalior",
    district: "Datia",
    totalRegistered: 4,
    profileChecked: 4,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
  {
    srNo: 7,
    division: "Gwalior",
    district: "Guna",
    totalRegistered: 15,
    profileChecked: 15,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
  {
    srNo: 8,
    division: "Gwalior",
    district: "Morena",
    totalRegistered: 7,
    profileChecked: 7,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
  {
    srNo: 9,
    division: "Gwalior",
    district: "Sheopur",
    totalRegistered: 8,
    profileChecked: 8,
    selfVerified: 8,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "8 (0.00 %)",
  },
  {
    srNo: 10,
    division: "Indore",
    district: "Indore",
    totalRegistered: 4,
    profileChecked: 4,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
  {
    srNo: 11,
    division: "Indore",
    district: "Khandwa",
    totalRegistered: 20,
    profileChecked: 20,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
  {
    srNo: 12,
    division: "Jabalpur",
    district: "Balaghat",
    totalRegistered: 18,
    profileChecked: 18,
    selfVerified: 0,
    changeRequest: 0,
    approved: 0,
    rejected: 0,
    pending: 0,
    totalVerification: "0 (0.00 %)",
  },
];

export const verificationStatisticData = [
  {
    srNo: 1,
    division: "Bhopal",
    district: "Raisen",
    totalRegistered: 7518,
    verified: 6377,
    pending: 223,
    rejected: 918,
  },
  {
    srNo: 2,
    division: "Bhopal",
    district: "Sehore",
    totalRegistered: 6787,
    verified: 4564,
    pending: 1381,
    rejected: 842,
  },
  {
    srNo: 3,
    division: "Bhopal",
    district: "Bhopal",
    totalRegistered: 6370,
    verified: 42,
    pending: 6133,
    rejected: 195,
  },
  {
    srNo: 4,
    division: "Bhopal",
    district: "Vidisha",
    totalRegistered: 7453,
    verified: 3480,
    pending: 3033,
    rejected: 940,
  },
  {
    srNo: 5,
    division: "Bhopal",
    district: "Rajgarh",
    totalRegistered: 8815,
    verified: 1811,
    pending: 6407,
    rejected: 597,
  },
  {
    srNo: 6,
    division: "Gwalior",
    district: "Sheopur",
    totalRegistered: 3008,
    verified: 531,
    pending: 2217,
    rejected: 260,
  },
  {
    srNo: 7,
    division: "Gwalior",
    district: "Morena",
    totalRegistered: 10466,
    verified: 114,
    pending: 10057,
    rejected: 295,
  },
  {
    srNo: 8,
    division: "Gwalior",
    district: "Bhind",
    totalRegistered: 8367,
    verified: 4352,
    pending: 3141,
    rejected: 874,
  },
  {
    srNo: 9,
    division: "Gwalior",
    district: "Gwalior",
    totalRegistered: 7672,
    verified: 6,
    pending: 6642,
    rejected: 1024,
  },
  {
    srNo: 10,
    division: "Gwalior",
    district: "Datia",
    totalRegistered: 4827,
    verified: 2037,
    pending: 2346,
    rejected: 444,
  },
  {
    srNo: 11,
    division: "Gwalior",
    district: "Shivpuri",
    totalRegistered: 9329,
    verified: 1,
    pending: 9147,
    rejected: 181,
  },
  {
    srNo: 12,
    division: "Gwalior",
    district: "Guna",
    totalRegistered: 6917,
    verified: 857,
    pending: 5974,
    rejected: 86,
  },
];

export const employeeReportData = [
  {
    srNo: 1,
    nameCode: "Ram Narayan Shrivastri [AA6580]",
    gender: "Male",
    panel: "",
    designation: "Principal HSS",
    postingDate: "09/10/2024",
    officeCode: "BEO, BERASIA [233201OBS01]",
    ddoCode: "NA",
  },
  {
    srNo: 2,
    nameCode: "Rajesh Kumar Namdev [AB1189]",
    gender: "Male",
    panel: "SSS-2 Social Science",
    designation: "Madhyamik Shikshak",
    postingDate: "",
    officeCode: "BRC, BERAISA [233201OBS02]",
    ddoCode: "BEO BERASIA (0532003006)",
  },
  {
    srNo: 3,
    nameCode: "Yashwant Sexena [AA4529]",
    gender: "Male",
    panel: "",
    designation: "Asstt Grade-2",
    postingDate: "",
    officeCode: "BEO, BERASIA [233201OBS01]",
    ddoCode: "BEO BERASIA (0532003006)",
  },
  {
    srNo: 4,
    nameCode: "Akhilesh Nigam [BU7621]",
    gender: "Male",
    panel: "",
    designation: "Asstt Grade-3",
    postingDate: "",
    officeCode: "BEO, BERASIA [233201OBS01]",
    ddoCode: "BEO BERASIA (0532003006)",
  },
  {
    srNo: 5,
    nameCode: "REENA DANGI [CC6697]",
    gender: "Male",
    panel: "",
    designation: "Asstt Grade-3",
    postingDate: "",
    officeCode: "BEO, BERASIA [233201OBS01]",
    ddoCode: "BEO BERASIA (0532003006)",
  },
  {
    srNo: 6,
    nameCode: "Lakshminarayan Sen [AA4530]",
    gender: "Male",
    panel: "",
    designation: "Peon-Regular",
    postingDate: "",
    officeCode: "BEO, BERASIA [233201OBS01]",
    ddoCode: "BEO BERASIA (0532003006)",
  },
  {
    srNo: 7,
    nameCode: "Anil Sharama [CA2412]",
    gender: "Male",
    panel: "",
    designation: "Peon-Regular",
    postingDate: "",
    officeCode: "BEO, BERASIA [233201OBS01]",
    ddoCode: "BEO BERASIA (0532003006)",
  },
  {
    srNo: 8,
    nameCode: "Avadh Vihari Mishra [BK2296]",
    gender: "Male",
    panel: "",
    designation: "Peon-Regular",
    postingDate: "",
    officeCode: "BEO, BERASIA [233201OBS01]",
    ddoCode: "BEO BERASIA (0532003006)",
  },
  {
    srNo: 9,
    nameCode: "Rajeev Bhargava [AA4995]",
    gender: "Male",
    panel: "SSS-3 General",
    designation: "Asstt Teacher(LDT)",
    postingDate: "",
    officeCode: "BRC, BERAISA [233201OBS02]",
    ddoCode: "BEO BERASIA (0532003006)",
  },
  {
    srNo: 10,
    nameCode: "Ram Ayodhya Prasad [AU2792]",
    gender: "Male",
    panel: "PR-HSS",
    designation: "Principal HSS",
    postingDate: "",
    officeCode: "BEO, BERASIA [233201OBS01]",
    ddoCode: "BEO BERASIA (0532003006)",
  },
];

export const verificationDetailData = [
  {
    srNo: 1,
    district: "Bhopal",
    nameCode: "Ravindra Uikey - [CA1693]",
    designation: "Asstt Grade-3",
    oisCode: "Director, Public Instructions - [233203OSD03]",
    status: "Pending",
  },
  {
    srNo: 2,
    district: "Bhopal",
    nameCode: "Praveena Kaushal - [CA1689]",
    designation: "Principal HS",
    oisCode: "Director, Public Instructions - [233203OSD03]",
    status: "Pending",
  },
  {
    srNo: 3,
    district: "Bhopal",
    nameCode: "Yashwant Sexena - [AA4529]",
    designation: "Asstt Grade-2",
    oisCode: "BEO, BERASIA - [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 4,
    district: "Bhopal",
    nameCode: "Akhilesh Nigam - [BU7621]",
    designation: "Asstt Grade-3",
    oisCode: "BEO, BERASIA - [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 5,
    district: "Bhopal",
    nameCode: "REENA DANGI - [CC6697]",
    designation: "Asstt Grade-3",
    oisCode: "BEO, BERASIA - [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 6,
    district: "Bhopal",
    nameCode: "Anil Sharama - [CA2412]",
    designation: "Peon-Regular",
    oisCode: "BEO, BERASIA - [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 7,
    district: "Bhopal",
    nameCode: "Avadh Vihari Mishra - [BK2296]",
    designation: "Peon-Regular",
    oisCode: "BEO, BERASIA - [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 8,
    district: "Bhopal",
    nameCode: "Lakshminarayan Sen - [AA4530]",
    designation: "Peon-Regular",
    oisCode: "BEO, BERASIA - [233201OBS01]",
    status: "Pending",
  },
  {
    srNo: 9,
    district: "Bhopal",
    nameCode: "Ram Ayodhya Prasad - [AU2792]",
    designation: "Principal HSS",
    oisCode: "BEO, BERASIA - [233201OBS01]",
    status: "Reject",
  },
  {
    srNo: 10,
    district: "Bhopal",
    nameCode: "Ram Narayan Shrivastri - [AA6580]",
    designation: "Principal HSS",
    oisCode: "BEO, BERASIA - [233201OBS01]",
    status: "Pending",
  },
];

export const employeeCustomizedData = [
  {
    srNo: 1,
    nameCode: "Ram Ayodhya Prasad [AU2792]",
    gender: "Male",
    officeCode: "233201OBS01",
    postingDate: "NA",
    ddoCode: "BEO BERASIA (0532003006)",
    designation: "Principal HSS",
    panel: "PR-HSS",
    status: "Verification pending",
  },
  {
    srNo: 2,
    nameCode: "Ram Narayan Shrivastri [AA6580]",
    gender: "Male",
    officeCode: "233201OBS01",
    postingDate: "09/10/2024",
    ddoCode: "NA",
    designation: "Principal HSS",
    panel: "NA",
    status: "Approved",
  },
  {
    srNo: 3,
    nameCode: "Yashwant Sexena [AA4529]",
    gender: "Male",
    officeCode: "233201OBS01",
    postingDate: "NA",
    ddoCode: "BEO BERASIA (0532003006)",
    designation: "Asstt Grade-2",
    panel: "NA",
    status: "Approved",
  },
  {
    srNo: 4,
    nameCode: "Akhilesh Nigam [BU7621]",
    gender: "Male",
    officeCode: "233201OBS01",
    postingDate: "NA",
    ddoCode: "BEO BERASIA (0532003006)",
    designation: "Asstt Grade-3",
    panel: "NA",
    status: "Approved",
  },
  {
    srNo: 5,
    nameCode: "REENA DANGI [CC6697]",
    gender: "Male",
    officeCode: "233201OBS01",
    postingDate: "NA",
    ddoCode: "BEO BERASIA (0532003006)",
    designation: "Asstt Grade-3",
    panel: "NA",
    status: "Approved",
  },
  {
    srNo: 6,
    nameCode: "Lakshminarayan Sen [AA4530]",
    gender: "Male",
    officeCode: "233201OBS01",
    postingDate: "NA",
    ddoCode: "BEO BERASIA (0532003006)",
    designation: "Peon-Regular",
    panel: "NA",
    status: "Approved",
  },
  {
    srNo: 7,
    nameCode: "Anil Sharama [CA2412]",
    gender: "Male",
    officeCode: "233201OBS01",
    postingDate: "NA",
    ddoCode: "BEO BERASIA (0532003006)",
    designation: "Peon-Regular",
    panel: "NA",
    status: "Approved",
  },
  {
    srNo: 8,
    nameCode: "Rajeev Bhargava [AA4995]",
    gender: "Male",
    officeCode: "233201OBS02",
    postingDate: "NA",
    ddoCode: "BEO BERASIA (0532003006)",
    designation: "Asstt Teacher(LDT)",
    panel: "SSS-3 General",
    status: "Approved",
  },
  {
    srNo: 9,
    nameCode: "Rajesh Kumar Namdev [AB1189]",
    gender: "Male",
    officeCode: "233201OBS02",
    postingDate: "NA",
    ddoCode: "BEO BERASIA (0532003006)",
    designation: "Madhyamik Shikshak",
    panel: "SSS-2 Social Science",
    status: "Approved",
  },
  {
    srNo: 10,
    nameCode: "Avadh Vihari Mishra [BK2296]",
    gender: "Male",
    officeCode: "233201OBS01",
    postingDate: "NA",
    ddoCode: "BEO BERASIA (0532003006)",
    designation: "Peon-Regular",
    panel: "NA",
    status: "Approved",
  },
];
