export const districtOptions = [
  { label: "All", value: "all" },
  { label: "Alirajpur(49)", value: "alirajpur" },
  { label: "Bhopal(01)", value: "bhopal" },
  { label: "Rajgarh(03)", value: "rajgarh" },
  { label: "Vidisha(27)", value: "vidisha" },
];

export const sectionOptions = [
  { label: "All", value: "all" },
  { label: "Est-1", value: "all" },
  { label: "Est-2", value: "all" },
  { label: "Est-3", value: "all" },
  { label: "Est-4", value: "all" },
  { label: "Health", value: "health" },
];

export const sectionOption = [
  { label: "All", value: "All" },
  { label: "RMSA", value: "RMSA" },
  { label: "Est-1", value: "Est-1" },
  { label: "Est-2", value: "Est-2" },
  { label: "IT Cell", value: "IT Cell" },
];

export const grievanceData = [
  {
    srNo: 1,
    grievanceNo: "GMSAW609900013",
    employeeName: "Dinesh Prasad Pandey [AW6099]",
    type: "Establishment Related",
    topic: "Transfer related problems",
    regDate: "18/05/2025",
    requestedBy: "Forwarded By DEO, REWA",
    forwardedOffice: "Forwarded To DEO, REWA",
    forwardDate: "18/05/2025",
    section: "NA",
  },
  {
    srNo: 2,
    grievanceNo: "GMSCC358501003",
    employeeName: "YACHANA MASIH [CC3585]",
    type: "Establishment Related",
    topic: "Transfer related problems",
    regDate: "21/05/2025",
    requestedBy: "Forwarded By DEO, JABALPUR",
    forwardedOffice: "Forwarded To DEO, JABALPUR",
    forwardDate: "21/05/2025",
    section: "NA",
  },
  {
    srNo: 3,
    grievanceNo: "GMSCD498100020",
    employeeName: "VARUN GAUR [CD4981]",
    type: "Establishment Related",
    topic: "Deputation",
    regDate: "19/05/2025",
    requestedBy: "Forwarded By BEO, REHLI",
    forwardedOffice: "Forwarded To BEO, REHLI",
    forwardDate: "19/05/2025",
    section: "NA",
  },
  {
    srNo: 4,
    grievanceNo: "GMSAA431101004",
    employeeName: "Anita Burbure [AA4311]",
    type: "Establishment Related",
    topic: "Time Pay Scale",
    regDate: "02/06/2025",
    requestedBy: "Forwarded By DEO, BHOPAL",
    forwardedOffice: "Forwarded To DEO, BHOPAL",
    forwardDate: "02/06/2025",
    section: "NA",
  },
  {
    srNo: 5,
    grievanceNo: "GMSAA535300022",
    employeeName: "Ramesh Kumar Malviya [AA5353]",
    type: "Financial Related",
    topic: "Allowances",
    regDate: "20/05/2025",
    requestedBy: "Forwarded By Joint Director, Bhopal",
    forwardedOffice: "Forwarded To Joint Director, Bhopal",
    forwardDate: "20/05/2025",
    section: "NA",
  },
];

// 10 Mock Data Records
export const mockGrievanceData = [
  {
    srNo: 1,
    grievanceNo: "GMSCD498100001",
    employee: "VARUN GAUR [CD4981]",
    type: "Establishment Related",
    topic: "Time Pay Scale",
    regDate: "17/05/2025",
    forwardedOffice: "BEO, REHLI",
    forwardDate: "17/05/2025",
    section: "",
  },
  {
    srNo: 2,
    grievanceNo: "GMSCD498100002",
    employee: "VARUN GAUR [CD4981]",
    type: "Establishment Related",
    topic: "senior Scale Second",
    regDate: "17/05/2025",
    forwardedOffice: "DEO, SAGAR",
    forwardDate: "17/05/2025",
    section: "",
  },
  {
    srNo: 3,
    grievanceNo: "GMSCD498100003",
    employee: "VARUN GAUR [CD4981]",
    type: "Establishment Related",
    topic: "Promotions",
    regDate: "17/05/2025",
    forwardedOffice: "Commissioner, Public Instructions",
    forwardDate: "17/05/2025",
    section: "Est-2",
  },
  {
    srNo: 4,
    grievanceNo: "GMSCD498100004",
    employee: "VARUN GAUR [CD4981]",
    type: "Others",
    topic: "Others",
    regDate: "17/05/2025",
    forwardedOffice: "Commissioner, Public Instructions",
    forwardDate: "17/05/2025",
    section: "RMSA",
  },
  {
    srNo: 5,
    grievanceNo: "GMSCD498100005",
    employee: "VARUN GAUR [CD4981]",
    type: "Financial Related",
    topic: "GPF FBF withdrawal",
    regDate: "17/05/2025",
    forwardedOffice: "Joint Director (Education), Sagar",
    forwardDate: "17/05/2025",
    section: "",
  },
  {
    srNo: 6,
    grievanceNo: "GMSCD498100006",
    employee: "VARUN GAUR [CD4981]",
    type: "Establishment Related",
    topic: "Time Pay Scale",
    regDate: "17/05/2025",
    forwardedOffice: "BEO, REHLI",
    forwardDate: "17/05/2025",
    section: "",
  },
  {
    srNo: 7,
    grievanceNo: "GMSCD498100007",
    employee: "VARUN GAUR [CD4981]",
    type: "Financial Related",
    topic: "Allowances",
    regDate: "17/05/2025",
    forwardedOffice: "Commissioner, Public Instructions",
    forwardDate: "17/05/2025",
    section: "Est-1",
  },
  {
    srNo: 8,
    grievanceNo: "GMSCD498100008",
    employee: "VARUN GAUR [CD4981]",
    type: "Financial Related",
    topic: "Recoveries",
    regDate: "17/05/2025",
    forwardedOffice: "Commissioner, Public Instructions",
    forwardDate: "17/05/2025",
    section: "RMSA",
  },
  {
    srNo: 9,
    grievanceNo: "GMSCD498100009",
    employee: "VARUN GAUR [CD4981]",
    type: "Establishment Related",
    topic: "Addition of name in gradation list",
    regDate: "17/05/2025",
    forwardedOffice: "Commissioner, Public Instructions",
    forwardDate: "17/05/2025",
    section: "RMSA",
  },
  {
    srNo: 10,
    grievanceNo: "GMSBP901000010",
    employee: "Panbeshwar Ahirwar [BP9010]",
    type: "Establishment Related",
    topic: "Time Pay Scale",
    regDate: "17/05/2025",
    forwardedOffice: "BEO, REHLI",
    forwardDate: "17/05/2025",
    section: "",
  },
];

//mock data
export const masterData = [
  {
    srNo: 1,
    districtName: "Guna",
    totalApps: 1,
    pending: 1,
    rejected: 0,
    disposed: 0,
    percent: "100%",
  },
  {
    srNo: 2,
    districtName: "Khandwa",
    totalApps: 1,
    pending: 1,
    rejected: 0,
    disposed: 0,
    percent: "100%",
  },
  {
    srNo: 3,
    districtName: "Rajgarh",
    totalApps: 1,
    pending: 1,
    rejected: 0,
    disposed: 0,
    percent: "100%",
  },
  {
    srNo: 4,
    districtName: "Bhopal",
    totalApps: 3,
    pending: 2,
    rejected: 1,
    disposed: 0,
    percent: "66%",
  },
  {
    srNo: 5,
    districtName: "Narmadapuram",
    totalApps: 1,
    pending: 1,
    rejected: 0,
    disposed: 0,
    percent: "100%",
  },
  {
    srNo: 6,
    districtName: "Sagar",
    totalApps: 16,
    pending: 3,
    rejected: 9,
    disposed: 4,
    percent: "18%",
  },
  {
    srNo: 7,
    districtName: "Jabalpur",
    totalApps: 1,
    pending: 1,
    rejected: 0,
    disposed: 0,
    percent: "100%",
  },
  {
    srNo: 8,
    districtName: "Rewa",
    totalApps: 1,
    pending: 1,
    rejected: 0,
    disposed: 0,
    percent: "100%",
  },
  {
    srNo: 9,
    districtName: "Sidhi",
    totalApps: 0,
    pending: 0,
    rejected: 0,
    disposed: 0,
    percent: "0",
  },
  {
    srNo: 10,
    districtName: "Singrauli",
    totalApps: 0,
    pending: 0,
    rejected: 0,
    disposed: 0,
    percent: "0",
  },
];

export const detailData = [
  {
    srNo: 1,
    grievanceNo: "GMSCD498100020",
    regDate: "19/05/2025",
    employee: "VARUN GAUR",
    type: "Establishment Related",
    topic: "Deputation",
    status: "Pending",
    forwardedOffice: "BEO, REHLI",
  },
  {
    srNo: 2,
    grievanceNo: "GMSCD498100016",
    regDate: "19/05/2025",
    employee: "VARUN GAUR",
    type: "Financial Related",
    topic: "House loan adjustment related problems",
    status: "Pending",
    forwardedOffice: "BEO, REHLI",
  },
  {
    srNo: 3,
    grievanceNo: "GMSCD498100003",
    regDate: "17/05/2025",
    employee: "VARUN GAUR",
    type: "Establishment Related",
    topic: "Promotions",
    status: "Pending",
    forwardedOffice: "Commissioner, Public Instructions",
  },
];

export const sectionData = [
  {
    srNo: 1,
    section: "RMSA",
    registered: 4,
    forwarded: 0,
    disposed: 2,
    rejected: 0,
    pending: 2,
  },
  {
    srNo: 2,
    section: "Est-1",
    registered: 1,
    forwarded: 0,
    disposed: 0,
    rejected: 1,
    pending: 0,
  },
  {
    srNo: 3,
    section: "Est-2",
    registered: 1,
    forwarded: 1,
    disposed: 0,
    rejected: 0,
    pending: 1,
  },
  {
    srNo: 4,
    section: "IT Cell",
    registered: 1,
    forwarded: 0,
    disposed: 0,
    rejected: 0,
    pending: 1,
  },
];
