import React from "react";
import {
  MdAccountBalance,
  MdAccountTree,
  MdAttachMoney,
  MdBadge,
  MdBarChart,
  MdBed,
  MdMenuBook as MdBooks,
  MdBusiness,
  MdCalendarToday,
  MdCategory,
  MdClass,
  MdDashboard,
  MdDescription,
  MdDirectionsBus,
  MdEvent,
  MdExtension,
  MdFavorite,
  MdDescription as MdFileSignature,
  MdForum,
  MdGavel,
  MdGrade,
  MdGroup,
  MdInventory,
  MdLanguage,
  MdLightbulb,
  MdLocalLibrary,
  MdMenuBook,
  MdPeople,
  MdPersonAdd,
  MdPhoneAndroid,
  MdPolicy,
  MdAccountTree as MdProjectDiagram,
  MdReceipt,
  MdRestaurant,
  MdSchedule,
  MdSchool,
  MdSearch,
  MdSecurity,
  MdSettings,
  MdSportsSoccer,
  MdStarHalf,
  MdSwapHoriz,
  MdDashboard as MdTachometer,
  MdTrendingUp,
  MdWarning,
  MdWork,
} from "react-icons/md";

// Mapping FontAwesome icon names to Material Design icons
const iconMap: Record<string, React.ElementType> = {
  "fa-cogs": MdSettings,
  "fa-users": MdPeople,
  "fa-users-cog": MdPeople,
  "fa-building": MdBusiness,
  "fa-graduation-cap": MdSchool,
  "fa-user-plus": MdPersonAdd,
  "fa-sitemap": MdAccountTree,
  "fa-bus": MdDirectionsBus,
  "fa-money-bill": MdAttachMoney,
  "fa-bed": MdBed,
  "fa-book": MdLocalLibrary,
  "fa-boxes": MdInventory,
  "fa-chart-line": MdTrendingUp,
  "fa-sections": MdCategory,
  "fa-utensils": MdRestaurant,
  "fa-hand-holding-heart": MdFavorite,
  "fa-briefcase": MdWork,
  "fa-calendar-check": MdCalendarToday,
  "fa-book-open": MdMenuBook,
  "fa-star": MdGrade,
  "fa-globe": MdLanguage,
  "fa-chart-bar": MdBarChart,
  "fa-file-alt": MdDescription,
  "fa-clock": MdSchedule,
  "fa-chalkboard-teacher": MdClass,
  "fa-star-half-alt": MdStarHalf,
  "fa-exchange-alt": MdSwapHoriz,
  "fa-lightbulb": MdLightbulb,
  "fa-books": MdBooks,
  "fa-calendar": MdEvent,
  "fa-comments": MdForum,
  "fa-user-friends": MdGroup,
  "fa-shield-alt": MdSecurity,
  "fa-futbol": MdSportsSoccer,
  "fa-search": MdSearch,
  "fa-mobile-alt": MdPhoneAndroid,
  "fa-plug": MdExtension,
  "fa-id-card": MdBadge,
  "fa-policy": MdPolicy,
  "fa-exclamation-triangle": MdWarning,
  "fa-file-invoice": MdReceipt,
  "fa-gavel": MdGavel,
  "fa-file-signature": MdFileSignature,
  "fa-university": MdAccountBalance,
  "fa-tachometer-alt": MdTachometer,
  "fa-project-diagram": MdProjectDiagram,
};

/**
 * Get React Icon component from FontAwesome icon name
 * @param iconName - FontAwesome icon class name (e.g., 'fa-cogs')
 * @returns React Icon component or MdDashboard as fallback
 */
export const getIcon = (iconName: string): React.ElementType => {
  // Normalize icon name to lowercase
  const normalizedName = iconName.toLowerCase();
  return iconMap[normalizedName] || MdDashboard;
};
