import React from 'react';
import {
  MdSettings,
  MdPeople,
  MdBusiness,
  MdSchool,
  MdPersonAdd,
  MdAccountTree,
  MdDirectionsBus,
  MdAttachMoney,
  MdBed,
  MdLocalLibrary,
  MdInventory,
  MdTrendingUp,
  MdCategory,
  MdRestaurant,
  MdFavorite,
  MdWork,
  MdCalendarToday,
  MdMenuBook,
  MdGrade,
  MdLanguage,
  MdBarChart,
  MdDescription,
  MdSchedule,
  MdClass,
  MdStarHalf,
  MdSwapHoriz,
  MdLightbulb,
  MdMenuBook as MdBooks,
  MdEvent,
  MdForum,
  MdGroup,
  MdSecurity,
  MdSportsSoccer,
  MdSearch,
  MdPhoneAndroid,
  MdExtension,
  MdBadge,
  MdPolicy,
  MdWarning,
  MdReceipt,
  MdGavel,
  MdDescription as MdFileSignature,
  MdAccountBalance,
  MdDashboard as MdTachometer,
  MdAccountTree as MdProjectDiagram,
  MdDashboard,
} from 'react-icons/md';

// Mapping FontAwesome icon names to Material Design icons
const iconMap: Record<string, React.ElementType> = {
  'fa-cogs': MdSettings,
  'fa-users': MdPeople,
  'fa-users-cog': MdPeople,
  'fa-building': MdBusiness,
  'fa-graduation-cap': MdSchool,
  'fa-user-plus': MdPersonAdd,
  'fa-sitemap': MdAccountTree,
  'fa-bus': MdDirectionsBus,
  'fa-money-bill': MdAttachMoney,
  'fa-bed': MdBed,
  'fa-book': MdLocalLibrary,
  'fa-boxes': MdInventory,
  'fa-chart-line': MdTrendingUp,
  'fa-sections': MdCategory,
  'fa-utensils': MdRestaurant,
  'fa-hand-holding-heart': MdFavorite,
  'fa-briefcase': MdWork,
  'fa-calendar-check': MdCalendarToday,
  'fa-book-open': MdMenuBook,
  'fa-star': MdGrade,
  'fa-globe': MdLanguage,
  'fa-chart-bar': MdBarChart,
  'fa-file-alt': MdDescription,
  'fa-clock': MdSchedule,
  'fa-chalkboard-teacher': MdClass,
  'fa-star-half-alt': MdStarHalf,
  'fa-exchange-alt': MdSwapHoriz,
  'fa-lightbulb': MdLightbulb,
  'fa-books': MdBooks,
  'fa-calendar': MdEvent,
  'fa-comments': MdForum,
  'fa-user-friends': MdGroup,
  'fa-shield-alt': MdSecurity,
  'fa-futbol': MdSportsSoccer,
  'fa-search': MdSearch,
  'fa-mobile-alt': MdPhoneAndroid,
  'fa-plug': MdExtension,
  'fa-id-card': MdBadge,
  'fa-policy': MdPolicy,
  'fa-exclamation-triangle': MdWarning,
  'fa-file-invoice': MdReceipt,
  'fa-gavel': MdGavel,
  'fa-file-signature': MdFileSignature,
  'fa-university': MdAccountBalance,
  'fa-tachometer-alt': MdTachometer,
  'fa-project-diagram': MdProjectDiagram,
};

/**
 * Get React Icon component from FontAwesome icon name
 * @param iconName - FontAwesome icon class name (e.g., 'fa-cogs')
 * @returns React Icon component or MdDashboard as fallback
 */
export const getIcon = (iconName: string): React.ElementType => {
  // Normalize icon name to lowercase
  const normalizedName = iconName.toLowerCase();
  return iconMap[normalizedName] || MdDashboard;
};
