export const classMasterMockData = [
  {
    id: 1,
    classNameEn: "Class IV",
    classNameHi: "Class IV",
    classCode: "4",
    status: "Yes",
  },
  {
    id: 2,
    classNameEn: "Class III",
    classNameHi: "Class III",
    classCode: "3",
    status: "Yes",
  },
  {
    id: 3,
    classNameEn: "Class II",
    classNameHi: "Class II",
    classCode: "2",
    status: "Yes",
  },
  {
    id: 4,
    classNameEn: "Class I",
    classNameHi: "Class I",
    classCode: "1",
    status: "Yes",
  },
];

export const designationTypeMockData = [
  {
    id: 1,
    typeNameEn: "Private Teaching",
    typeNameHi: "निजी शिक्षण",
    typeCode: "9",
    status: "Yes",
  },
  {
    id: 2,
    typeNameEn: "Non-Teaching",
    typeNameHi: "गैर शिक्षण",
    typeCode: "8",
    status: "Yes",
  },
  {
    id: 3,
    typeNameEn: "Hostel",
    typeNameHi: "छात्रावास",
    typeCode: "7",
    status: "Yes",
  },
  {
    id: 4,
    typeNameEn: "Other Department",
    typeNameHi: "अन्य विभाग",
    typeCode: "6",
    status: "Yes",
  },
  {
    id: 5,
    typeNameEn: "Teaching",
    typeNameHi: "शिक्षण",
    typeCode: "5",
    status: "Yes",
  },
  {
    id: 6,
    typeNameEn: "State",
    typeNameHi: "राज्य",
    typeCode: "4",
    status: "Yes",
  },
  {
    id: 7,
    typeNameEn: "Ministry",
    typeNameHi: "मंत्रालय",
    typeCode: "3",
    status: "Yes",
  },
  {
    id: 8,
    typeNameEn: "Executive",
    typeNameHi: "कार्यकारी",
    typeCode: "2",
    status: "Yes",
  },
];

export const designationMasterMockData = [
  {
    id: 1,
    class: "Class I",
    post: "Regular/Permanent",
    type: "Private Teaching",
    nameEn: "Principal/Director/Shikshak",
    seqNo: "1",
    code: "211",
    status: "Yes",
  },
  {
    id: 2,
    class: "Class I",
    post: "Regular/Permanent",
    type: "Teaching",
    nameEn: "Prathmik Shikshak -IT",
    seqNo: "1",
    code: "589",
    status: "Yes",
  },
  {
    id: 3,
    class: "Class I",
    post: "Regular/Permanent",
    type: "Teaching",
    nameEn: "Prathmik Shikshak -Music- Gayan/Vadan",
    seqNo: "1",
    code: "588",
    status: "Yes",
  },
  {
    id: 4,
    class: "Class I",
    post: "Regular/Permanent",
    type: "Teaching",
    nameEn: "Career Counselor",
    seqNo: "1",
    code: "587",
    status: "Yes",
  },
  {
    id: 5,
    class: "Class I",
    post: "Regular/Permanent",
    type: "Teaching",
    nameEn: "Pre Primary Teacher",
    seqNo: "1",
    code: "586",
    status: "Yes",
  },
  {
    id: 6,
    class: "Class I",
    post: "Regular/Permanent",
    type: "Teaching",
    nameEn: "Madhyamik Shikshak -Music-Gayan/Vadan",
    seqNo: "1",
    code: "585",
    status: "Yes",
  },
  {
    id: 7,
    class: "Class I",
    post: "Regular/Permanent",
    type: "Teaching",
    nameEn: "Prathmik Shikshak -Music-Nrity(Dance)",
    seqNo: "1",
    code: "584",
    status: "Yes",
  },
  {
    id: 8,
    class: "Class I",
    post: "Regular/Permanent",
    type: "Teaching",
    nameEn: "Madhyamik Shikshak -IT",
    seqNo: "1",
    code: "583",
    status: "Yes",
  },
  {
    id: 9,
    class: "Class I",
    post: "Regular/Permanent",
    type: "Teaching",
    nameEn: "Prathmik Shikshak -Khel",
    seqNo: "1",
    code: "582",
    status: "Yes",
  },
];

export const sectionMasterMockData = [
  {
    id: 1,
    sectionNameEn: "TMC",
    sectionNameHi: "NA",
    sectionCode: "21",
    status: "Yes",
  },
  {
    id: 2,
    sectionNameEn: "Physical Education",
    sectionNameHi: "NA",
    sectionCode: "20",
    status: "Yes",
  },
  {
    id: 3,
    sectionNameEn: "CPI",
    sectionNameHi: "NA",
    sectionCode: "19",
    status: "Yes",
  },
  {
    id: 4,
    sectionNameEn: "Enter Sectionf",
    sectionNameHi: "अनुभाग",
    sectionCode: "02",
    status: "No",
  },
  {
    id: 5,
    sectionNameEn: "NSDL",
    sectionNameHi: "NA",
    sectionCode: "17",
    status: "Yes",
  },
  {
    id: 6,
    sectionNameEn: "Grant",
    sectionNameHi: "NA",
    sectionCode: "16",
    status: "Yes",
  },
  {
    id: 7,
    sectionNameEn: "Finance",
    sectionNameHi: "NA",
    sectionCode: "15",
    status: "Yes",
  },
  {
    id: 8,
    sectionNameEn: "IT Cell",
    sectionNameHi: "NA",
    sectionCode: "14",
    status: "Yes",
  },
];

export const payCommissionMasterMockData = [
  {
    id: 1,
    payType: "Grade Pay",
    commission: "Forth Pay Commission",
    mappedDA: "Yes",
    effectiveDate: "2024-10-01",
    seqNo: "4",
    code: "04",
    status: "Yes",
  },
  {
    id: 2,
    payType: "Grade Pay",
    commission: "Fifth Pay Commission",
    mappedDA: "Yes",
    effectiveDate: "2024-10-01",
    seqNo: "3",
    code: "03",
    status: "Yes",
  },
  {
    id: 3,
    payType: "Grade Pay",
    commission: "Sixth Pay Commission",
    mappedDA: "Yes",
    effectiveDate: "2024-10-01",
    seqNo: "2",
    code: "02",
    status: "Yes",
  },
  {
    id: 4,
    payType: "Level Pay",
    commission: "Seventh Pay Commission",
    mappedDA: "Yes",
    effectiveDate: "2024-10-01",
    seqNo: "1",
    code: "01",
    status: "Yes",
  },
];

export const payScaleMasterMockData = [
  {
    id: 1,
    payCommission: "Seventh Pay Commission",
    payScale: "37400-67000",
    effectiveDate: "2024/10/01",
    status: "Yes",
  },
  {
    id: 2,
    payCommission: "Seventh Pay Commission",
    payScale: "15600-39100",
    effectiveDate: "2024/10/23",
    status: "Yes",
  },
  {
    id: 3,
    payCommission: "Seventh Pay Commission",
    payScale: "9300-34800",
    effectiveDate: "2024/10/01",
    status: "Yes",
  },
  {
    id: 4,
    payCommission: "Seventh Pay Commission",
    payScale: "5200-20200",
    effectiveDate: "2024/10/01",
    status: "Yes",
  },
  {
    id: 5,
    payCommission: "Seventh Pay Commission",
    payScale: "44400-7440",
    effectiveDate: "2024/10/01",
    status: "Yes",
  },
];

export const gradePayMasterMockData = [];

export const levelMasterMockData = [
  {
    id: 1,
    commission: "Seventh Pay Commission",
    payScale: "37400-67000",
    gradeLevel: "Level-17",
    effectiveDate: "10/01/2024",
    status: "Yes",
  },
  {
    id: 2,
    commission: "Seventh Pay Commission",
    payScale: "37400-67000",
    gradeLevel: "Level-16",
    effectiveDate: "10/01/2024",
    status: "Yes",
  },
  {
    id: 3,
    commission: "Seventh Pay Commission",
    payScale: "37400-67000",
    gradeLevel: "Level-15",
    effectiveDate: "10/01/2024",
    status: "Yes",
  },
  {
    id: 4,
    commission: "Seventh Pay Commission",
    payScale: "15600-39100",
    gradeLevel: "Level-14",
    effectiveDate: "10/01/2024",
    status: "Yes",
  },
  {
    id: 5,
    commission: "Seventh Pay Commission",
    payScale: "15600-39100",
    gradeLevel: "Level-13",
    effectiveDate: "10/01/2024",
    status: "Yes",
  },
  {
    id: 6,
    commission: "Seventh Pay Commission",
    payScale: "15600-39100",
    gradeLevel: "Level-12",
    effectiveDate: "10/01/2024",
    status: "Yes",
  },
  {
    id: 7,
    commission: "Seventh Pay Commission",
    payScale: "9300-34800",
    gradeLevel: "Level-11",
    effectiveDate: "10/01/2024",
    status: "Yes",
  },
  {
    id: 8,
    commission: "Seventh Pay Commission",
    payScale: "9300-34800",
    gradeLevel: "Level-10",
    effectiveDate: "10/01/2024",
    status: "Yes",
  },
  {
    id: 9,
    commission: "Seventh Pay Commission",
    payScale: "9300-34800",
    gradeLevel: "Level-9",
    effectiveDate: "10/01/2024",
    status: "Yes",
  },
  {
    id: 10,
    commission: "Seventh Pay Commission",
    payScale: "9300-34800",
    gradeLevel: "Level-8",
    effectiveDate: "10/01/2024",
    status: "Yes",
  },
];

export const levelBasicPayMockData = [
  {
    id: 1,
    levelName: "Level-5",
    basicPay: "70000",
    effectiveDate: "01/10/2024",
    status: "Yes",
  },
  {
    id: 2,
    levelName: "Level-5",
    basicPay: "68000",
    effectiveDate: "01/10/2024",
    status: "Yes",
  },
  {
    id: 3,
    levelName: "Level-5",
    basicPay: "66000",
    effectiveDate: "01/10/2024",
    status: "Yes",
  },
  {
    id: 4,
    levelName: "Level-5",
    basicPay: "64100",
    effectiveDate: "01/10/2024",
    status: "Yes",
  },
  {
    id: 5,
    levelName: "Level-5",
    basicPay: "62200",
    effectiveDate: "01/10/2024",
    status: "Yes",
  },
  {
    id: 6,
    levelName: "Level-5",
    basicPay: "60400",
    effectiveDate: "01/10/2024",
    status: "Yes",
  },
  {
    id: 7,
    levelName: "Level-5",
    basicPay: "58600",
    effectiveDate: "01/10/2024",
    status: "Yes",
  },
  {
    id: 8,
    levelName: "Level-5",
    basicPay: "56900",
    effectiveDate: "01/10/2024",
    status: "Yes",
  },
  {
    id: 9,
    levelName: "Level-5",
    basicPay: "55200",
    effectiveDate: "01/10/2024",
    status: "Yes",
  },
  {
    id: 10,
    levelName: "Level-5",
    basicPay: "53600",
    effectiveDate: "01/10/2024",
    status: "Yes",
  },
];

export const appointmentDepartmentMockData = [
  {
    id: 1,
    departmentNameEn: "School Edu test",
    departmentNameHi: "विभाग",
    departmentCode: "09",
    effectiveDate: "2024-06-13",
    status: "Yes",
  },
  {
    id: 2,
    departmentNameEn: "Department",
    departmentNameHi: "विभाग",
    departmentCode: "01",
    effectiveDate: "2024-06-08",
    status: "Yes",
  },
  {
    id: 3,
    departmentNameEn: "Education",
    departmentNameHi: "विभाग",
    departmentCode: "01",
    effectiveDate: "2024-06-08",
    status: "Yes",
  },
  {
    id: 4,
    departmentNameEn: "Education Department",
    departmentNameHi: "विभाग",
    departmentCode: "09",
    effectiveDate: "2024-06-05",
    status: "Yes",
  },
  {
    id: 5,
    departmentNameEn: "Department of eductaion",
    departmentNameHi: "शिक्षा विभाग",
    departmentCode: "09",
    effectiveDate: "2024-05-21",
    status: "Yes",
  },
  {
    id: 6,
    departmentNameEn: "Madarsa Unrecognized",
    departmentNameHi: "मदरसा गैर मान्यता प्राप्त",
    departmentCode: "98",
    effectiveDate: "2024-01-25",
    status: "Yes",
  },
  {
    id: 7,
    departmentNameEn: "Madrasa Aided Recognized",
    departmentNameHi: "मदरसा सहायता प्राप्त (मान्यता प्राप्त)",
    departmentCode: "99",
    effectiveDate: "2024-01-25",
    status: "Yes",
  },
  {
    id: 8,
    departmentNameEn: "Madrasa Private Unaided Recognized",
    departmentNameHi: "मदरसा निजी गैर सहायता प्राप्त (मान्यता प्राप्त)",
    departmentCode: "97",
    effectiveDate: "2024-01-25",
    status: "Yes",
  },
  {
    id: 9,
    departmentNameEn: "Unrecognized",
    departmentNameHi: "पहचानने अयोग्य",
    departmentCode: "08",
    effectiveDate: "2024-01-25",
    status: "Yes",
  },
];

export const casteMasterMockData = [
  { id: 1, casteNameEn: "General", casteNameHi: "NA", status: "Yes" },
  { id: 2, casteNameEn: "OBC", casteNameHi: "NA", status: "Yes" },
  { id: 3, casteNameEn: "ST", casteNameHi: "NA", status: "Yes" },
  { id: 4, casteNameEn: "SC", casteNameHi: "NA", status: "Yes" },
];

export const bloodGroupMasterMockData = [
  { id: 1, bloodGroupName: "A+", status: "Yes" },
  { id: 2, bloodGroupName: "A-", status: "Yes" },
  { id: 3, bloodGroupName: "B+", status: "Yes" },
  { id: 4, bloodGroupName: "B-", status: "Yes" },
  { id: 5, bloodGroupName: "AB+", status: "Yes" },
  { id: 6, bloodGroupName: "AB-", status: "Yes" },
  { id: 7, bloodGroupName: "O+", status: "Yes" },
  { id: 8, bloodGroupName: "O-", status: "Yes" },
  { id: 9, bloodGroupName: "Not Known", status: "Yes" },
];

export const qualificationMasterMockData = [
  {
    id: 1,
    qualNameEn: "Other",
    qualNameHi: "अन्य",
    subject: "Other",
    code: "Q018",
    status: "Yes",
  },
  {
    id: 2,
    qualNameEn: "GNM nursing ,bsc,peramedi",
    qualNameHi: "जीएनएम नर्सिंग, बीएससी, पैरामेडिकल",
    subject: "Nursing",
    code: "Q017",
    status: "Yes",
  },
  {
    id: 3,
    qualNameEn: "MSc Nursing",
    qualNameHi: "एमएससी नर्सिंग",
    subject: "Nursing",
    code: "Q016",
    status: "Yes",
  },
  {
    id: 4,
    qualNameEn: "Bsc nursing+MSC nursing",
    qualNameHi: "बीएससी नर्सिंग + एमएससी नर्सिंग",
    subject: "Nursing",
    code: "Q015",
    status: "Yes",
  },
  {
    id: 5,
    qualNameEn: "Bost B. Bsc nursing",
    qualNameHi: "पोस्ट बी. बीएससी नर्सिंग",
    subject: "Nursing",
    code: "Q014",
    status: "Yes",
  },
  {
    id: 6,
    qualNameEn: "P.B.Bsc Nursing",
    qualNameHi: "पी.बी.बीएससी नर्सिंग",
    subject: "Nursing",
    code: "Q013",
    status: "Yes",
  },
  {
    id: 7,
    qualNameEn: "Post BSC nursing + GNM nursing",
    qualNameHi: "पोस्ट बीएससी नर्सिंग + जीएनएम नर्सिंग",
    subject: "Nursing",
    code: "Q012",
    status: "Yes",
  },
  {
    id: 8,
    qualNameEn: "DGNM",
    qualNameHi: "डीजीएनएम",
    subject: "Nursing",
    code: "Q011",
    status: "Yes",
  },
  {
    id: 9,
    qualNameEn: "GRADUATE BSC NURSING",
    qualNameHi: "स्नातक बीएससी नर्सिंग",
    subject: "Nursing",
    code: "Q010",
    status: "Yes",
  },
  {
    id: 10,
    qualNameEn: "G.N.M.",
    qualNameHi: "जी.एन.एम.",
    subject: "Nursing",
    code: "Q009",
    status: "Yes",
  },
];

export const subCasteMasterMockData = [
  {
    id: 1,
    casteName: "General",
    subCasteNameEn: "Brahmin",
    subCasteNameHi: "ब्राह्मण",
    status: "Yes",
  },
];

export const postMasterMockData = [
  {
    id: 1,
    postNameEn: "Job Rate Employee",
    postNameHi: "Job Rate Employee",
    postCode: "11",
    status: "Yes",
  },
  {
    id: 2,
    postNameEn: "Daily Wages Federation",
    postNameHi: "Daily Wages Federation",
    postCode: "10",
    status: "Yes",
  },
  {
    id: 3,
    postNameEn: "Daily Wages Employee",
    postNameHi: "Daily Wages Employee",
    postCode: "9",
    status: "Yes",
  },
  {
    id: 4,
    postNameEn: "Contractual Employee",
    postNameHi: "Contractual Employee",
    postCode: "8",
    status: "Yes",
  },
  {
    id: 5,
    postNameEn: "Deputation Employee",
    postNameHi: "Deputation Employee",
    postCode: "7",
    status: "Yes",
  },
  {
    id: 6,
    postNameEn: "Outsource Employee",
    postNameHi: "Outsource Employee",
    postCode: "6",
    status: "Yes",
  },
  {
    id: 7,
    postNameEn: "Theka Shramik",
    postNameHi: "Theka Shramik",
    postCode: "5",
    status: "Yes",
  },
  {
    id: 8,
    postNameEn: "Samvida Employee",
    postNameHi: "Samvida Employee",
    postCode: "4",
    status: "Yes",
  },
  {
    id: 9,
    postNameEn: "Contigent Employee",
    postNameHi: "Contigent Employee",
    postCode: "3",
    status: "Yes",
  },
  {
    id: 10,
    postNameEn: "Fixed Employee",
    postNameHi: "Fixed Employee",
    postCode: "2",
    status: "Yes",
  },
];

export const schoolSubCategoryMockData = [
  {
    id: 1,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 1",
    classCode: "01",
  },
  {
    id: 2,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 2",
    classCode: "02",
  },
  {
    id: 3,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 3",
    classCode: "03",
  },
  {
    id: 4,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 4",
    classCode: "04",
  },
  {
    id: 5,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 5",
    classCode: "05",
  },
  {
    id: 6,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 6",
    classCode: "06",
  },
  {
    id: 7,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 7",
    classCode: "07",
  },
  {
    id: 8,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 8",
    classCode: "08",
  },
  {
    id: 9,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 9",
    classCode: "09",
  },
  {
    id: 10,
    subCategoryName: "Higher Secondary with grades 1 to 12 (PRY-UPR-SEC-HSEC)",
    className: "Class - 10",
    classCode: "10",
  },
];

export const handicappedTypeMockData = [
  {
    id: 1,
    typeNameEn: "locomotor Disablity",
    typeNameHi: "लोकोमोटर विकलांगता",
    type: "LO",
    code: "13",
    status: "Yes",
  },
  {
    id: 2,
    typeNameEn: "Physical Handicap",
    typeNameHi: "शारीरिक बाधा",
    type: "PH",
    code: "12",
    status: "Yes",
  },
  {
    id: 3,
    typeNameEn: "Visually Impaired - VI",
    typeNameHi: "दृष्टि हीन",
    type: "VI",
    code: "11",
    status: "Yes",
  },
  {
    id: 4,
    typeNameEn: "Other",
    typeNameHi: "अन्य",
    type: "OT",
    code: "10",
    status: "Yes",
  },
  {
    id: 5,
    typeNameEn: "Celebral Palsi",
    typeNameHi: "सेरेब्रल पाल्सी",
    type: "CP",
    code: "9",
    status: "Yes",
  },
  {
    id: 6,
    typeNameEn: "Mutiple-Disability",
    typeNameHi: "बहु विकलांगता",
    type: "MD",
    code: "8",
    status: "Yes",
  },
  {
    id: 7,
    typeNameEn: "Learning Disbaility",
    typeNameHi: "अधिगम विकलांगता",
    type: "LD",
    code: "5",
    status: "Yes",
  },
  {
    id: 8,
    typeNameEn: "Mental retarded",
    typeNameHi: "मानसिक रुग्णता/मेंटल रिटार्डनेस",
    type: "MR",
    code: "4",
    status: "Yes",
  },
  {
    id: 9,
    typeNameEn: "OHTHOPEDIC",
    typeNameHi: "अस्थिबाधिता/शिथिलांग/लेपेरेसी/क्योर्ड",
    type: "OH",
    code: "3",
    status: "Yes",
  },
  {
    id: 10,
    typeNameEn: "Visually Handicapped",
    typeNameHi: "दृष्टि बाधित",
    type: "VH",
    code: "2",
    status: "Yes",
  },
];

export const criticalIllnessMockData = [
  { id: 1, nameEn: "Paralysis", nameHi: "लकवा ग्रस्त", status: "Yes" },
  {
    id: 2,
    nameEn: "Open heart Surgery",
    nameHi: "ओपन हार्ट सर्जरी",
    status: "Yes",
  },
  {
    id: 3,
    nameEn: "Kidney Transplant",
    nameHi: "गुर्दा प्रत्यारोपण",
    status: "Yes",
  },
  { id: 4, nameEn: "Brain Tumor", nameHi: "ब्रेन ट्यूमर", status: "Yes" },
  { id: 5, nameEn: "Cancer", nameHi: "कैंसर", status: "Yes" },
  { id: 6, nameEn: "Illness", nameHi: "NA", status: "Yes" },
];
